// This file is generated by 'data/gen.ts'!
// 
// The data in this file is not licensed under the same license as the rest of the
// project. It is derived from the Satisfactory Wiki, which in turn took it from the
// game. See the main README for more information.
import type { Item } from ".";

export const ITEMS = {
    "uranium-waste": { // Desc_NuclearWaste_C
        "name": "Uranium Waste",
        "description": "The by-product of consuming Uranium Fuel Rods in a Nuclear Power Plant.<br>Non-Fissile Uranium can be extracted. Handle with caution.<br>Caution: HIGHLY Radioactive."
    },
    "plutonium-waste": { // Desc_PlutoniumWaste_C
        "name": "Plutonium Waste",
        "description": "The by-product of consuming Plutonium Fuel Rods in a Nuclear Power Plant.<br>Must be stored in a safe location. Handle with caution.<br>Caution: EXTREMELY Radioactive."
    },
    "concrete": { // Desc_Cement_C
        "name": "Concrete",
        "description": "Used for building.<br>Good for stable Foundations."
    },
    "silica": { // Desc_Silica_C
        "name": "Silica",
        "description": "Derived from Raw Quartz. Commonly used to create glass structures, in advanced refinement processes, and for alternative production of electronics."
    },
    "iron-plate": { // Desc_IronPlate_C
        "name": "Iron Plate",
        "description": "Used for crafting.<br>One of the most basic parts."
    },
    "steel-beam": { // Desc_SteelPlate_C
        "name": "Steel Beam",
        "description": "Primarily used when constructing slightly more advanced buildings."
    },
    "aluminum-ingot": { // Desc_AluminumIngot_C
        "name": "Aluminum Ingot",
        "description": "Smelted from Aluminum Scrap, which is refined from Alumina Solution.<br>Used to produce specialized aluminum-based parts."
    },
    "battery": { // Desc_Battery_C
        "name": "Battery",
        "description": "Primarily used as fuel for Drones and vehicles."
    },
    "packaged-fuel": { // Desc_Fuel_C
        "name": "Packaged Fuel",
        "description": "Fuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack."
    },
    "packaged-ionized-fuel": { // Desc_PackagedIonizedFuel_C
        "name": "Packaged Ionized Fuel",
        "description": "Ionized Fuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack."
    },
    "packaged-rocket-fuel": { // Desc_PackagedRocketFuel_C
        "name": "Packaged Rocket Fuel",
        "description": "Rocket Fuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack."
    },
    "packaged-turbofuel": { // Desc_TurboFuel_C
        "name": "Packaged Turbofuel",
        "description": "Turbofuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack."
    },
    "iodine-infused-filter": { // Desc_HazmatFilter_C
        "name": "Iodine-Infused Filter",
        "description": "Absorbs radioactive particles when used with the Hazmat Suit."
    },
    "compacted-coal": { // Desc_CompactedCoal_C
        "name": "Compacted Coal",
        "description": "A much more efficient alternative to Coal. Used as fuel for vehicles and Coal-Powered Generators."
    },
    "packaged-heavy-oil-residue": { // Desc_PackagedOilResidue_C
        "name": "Packaged Heavy Oil Residue",
        "description": "Heavy Oil Residue, packaged for alternative transport. Can be used as fuel for vehicles."
    },
    "petroleum-coke": { // Desc_PetroleumCoke_C
        "name": "Petroleum Coke",
        "description": "Used for crafting.<br>A carbon-rich material distilled from Heavy Oil Residue. <br>Used as a less efficient Coal replacement."
    },
    "packaged-oil": { // Desc_PackagedOil_C
        "name": "Packaged Oil",
        "description": "Crude Oil, packaged for alternative transport. Can be used as fuel for vehicles."
    },
    "iron-rod": { // Desc_IronRod_C
        "name": "Iron Rod",
        "description": "Used for crafting.<br>One of the most basic parts."
    },
    "wire": { // Desc_Wire_C
        "name": "Wire",
        "description": "Used for crafting.<br>One of the most basic parts."
    },
    "cable": { // Desc_Cable_C
        "name": "Cable",
        "description": "Used for crafting.<br>Primarily used to build Power Lines."
    },
    "iron-ingot": { // Desc_IronIngot_C
        "name": "Iron Ingot",
        "description": "Used for crafting the most basic parts."
    },
    "reinforced-iron-plate": { // Desc_IronPlateReinforced_C
        "name": "Reinforced Iron Plate",
        "description": "Used for crafting.<br>A sturdier and more durable Iron Plate."
    },
    "rotor": { // Desc_Rotor_C
        "name": "Rotor",
        "description": "Used for crafting.<br>The moving parts of a motor."
    },
    "fuel": { // Desc_LiquidFuel_C
        "name": "Fuel",
        "description": "Can be used as-is to generate power, or packaged to be used as fuel for vehicles or the Jetpack."
    },
    "rocket-fuel": { // Desc_RocketFuel_C
        "name": "Rocket Fuel",
        "description": "A high-impulse compressed gas fuel.<br>Can be used as-is to power Fuel-Powered Generators, or packaged to be used as fuel for vehicles or the Jetpack."
    },
    "copper-sheet": { // Desc_CopperSheet_C
        "name": "Copper Sheet",
        "description": "Used for crafting.<br>Primarily used for Pipelines due to its high corrosion resistance."
    },
    "modular-frame": { // Desc_ModularFrame_C
        "name": "Modular Frame",
        "description": "Used for crafting.<br>A multipurpose building block."
    },
    "screw": { // Desc_IronScrew_C
        "name": "Screw",
        "description": "Used for crafting.<br>One of the most basic parts."
    },
    "nitric-acid": { // Desc_NitricAcid_C
        "name": "Nitric Acid",
        "description": "Produced when Nitrogen Gas reacts with Water. Its high corrosiveness and oxidizing properties make it an excellent choice for refinement and fuel production processes."
    },
    "turbofuel": { // Desc_LiquidTurboFuel_C
        "name": "Turbofuel",
        "description": "A more efficient alternative to Fuel. Can be used as-is to generate power, or packaged to be used as fuel for vehicles."
    },
    "empty-fluid-tank": { // Desc_GasTank_C
        "name": "Empty Fluid Tank",
        "description": "Used to package gases and volatile liquids for transportation."
    },
    "crystal-oscillator": { // Desc_CrystalOscillator_C
        "name": "Crystal Oscillator",
        "description": "An electronic oscillator circuit that uses the mechanical resonance of a vibrating crystal to create an electrical signal with a precise frequency."
    },
    "motor": { // Desc_Motor_C
        "name": "Motor",
        "description": "Creates a mechanical force that is used to move things from machines to vehicles."
    },
    "dark-matter-crystal": { // Desc_DarkMatter_C
        "name": "Dark Matter Crystal",
        "description": "Concentrated Dark Matter Residue that is isolated within a crystalline vessel. This form of containment allows for utilising Dark Matter reliably in other production processes.<br>Power Usage: 500-1500 MW (1000 MW average)."
    },
    "ionized-fuel": { // Desc_IonizedFuel_C
        "name": "Ionized Fuel",
        "description": "Fuel that has been ionized, allowing it to deliver incredible output.<br>Can be used as-is to power Fuel-Powered Generators, or packaged to be used as fuel for vehicles or the Jetpack."
    },
    "supercomputer": { // Desc_ComputerSuper_C
        "name": "Supercomputer",
        "description": "The next-gen version of a Computer."
    },
    "cooling-system": { // Desc_CoolingSystem_C
        "name": "Cooling System",
        "description": "Keeps advanced parts and buildings from exceeding efficient temperature levels."
    },
    "ficsite-trigon": { // Desc_FicsiteMesh_C
        "name": "Ficsite Trigon",
        "description": "The Ficsite Trigon, made from Ficsite Ingots, is perfectly shaped for all construction challenges. It's performance is so exceptional, it basically solved structural engineering."
    },
    "turbo-motor": { // Desc_MotorLightweight_C
        "name": "Turbo Motor",
        "description": "A more complex and powerful version of the regular Motor."
    },
    "time-crystal": { // Desc_TimeCrystal_C
        "name": "Time Crystal",
        "description": "Time Crystals are Diamonds that have been reconfigured on a sub-atomic level in the Converter to retain a time-periodic self-organizing structure. This allows them to be used in the development of quantum processing and storage technologies."
    },
    "dark-matter-residue": { // Desc_DarkEnergy_C
        "name": "Dark Matter Residue",
        "description": "Produced as a by-product of Quantum Encoding processes and alternatively generated in the Converter.<br>Various fields of science are still debating the nature and properties of Dark Matter. Meanwhile, FICSIT has found several applications for it in space-time manipulation."
    },
    "reanimated-sam": { // Desc_SAMIngot_C
        "name": "Reanimated SAM",
        "description": "The active and contained form of the Strange Alien Matter.<br>Proper electromagnetic containment is required, as it appears to be able to manipulate the atomic bonds of any matter it comes into contact with."
    },
    "excited-photonic-matter": { // Desc_QuantumEnergy_C
        "name": "Excited Photonic Matter",
        "description": "Excited Photonic Matter is essential for all production processes in the Quantum Encoder.<br>Formed in the Converter by inducing intense photon interactions through exposure to SAM in a high-energy environment."
    },
    "diamonds": { // Desc_Diamond_C
        "name": "Diamonds",
        "description": "Synthetic Diamonds produced by exposing Coal to extreme heat and pressure.<br>Used in the production of Time Crystals and Dark Matter Crystals.<br>Power Usage: 250-750 MW (500 MW average)."
    },
    "alclad-aluminum-sheet": { // Desc_AluminumPlate_C
        "name": "Alclad Aluminum Sheet",
        "description": "Used to make products that require high heat conduction or a high specific strength. Thin, lightweight, and highly durable."
    },
    "superposition-oscillator": { // Desc_QuantumOscillator_C
        "name": "Superposition Oscillator",
        "description": "An oscillator circuit that uses the mechanical resonance of a vibrating crystal to create a string vibration with a precise frequency. Often used in teleportation technology and dimensional manipulation."
    },
    "neural-quantum-processor": { // Desc_TemporalProcessor_C
        "name": "Neural-Quantum Processor",
        "description": "The Neural-Quantum Processor utilizes a combination of neural network architecture and quantum computing techniques to achieve unprecedented performance. This technology has enabled some of FICSIT's biggest advancements in artificial intelligence and relativistic engineering."
    },
    "ai-expansion-server": { // Desc_SpaceElevatorPart_12_C
        "name": "AI Expansion Server",
        "description": "Project Part #12. Ship via the Space Elevator to complete phases of Project Assembly.<br>Power Usage: 1500-2500 MW (2000 MW average).<br>Growth is the metric by which we measure success."
    },
    "magnetic-field-generator": { // Desc_SpaceElevatorPart_6_C
        "name": "Magnetic Field Generator",
        "description": "Project Part #7. Ship via the Space Elevator to complete phases of Project Assembly.<br>These modular generators use superconducting magnets and vast amounts of electricity to produce a powerful and easily expandable magnetic field."
    },
    "sam-fluctuator": { // Desc_SAMFluctuator_C
        "name": "SAM Fluctuator",
        "description": "The SAM Fluctuator is able to regulate and direct the behaviour of Reanimated SAM through the application of electric charges with varying frequencies.<br>This control facilitates technologies such as matter-to-energy conversion and spatiotemporal matter manipulation."
    },
    "steel-pipe": { // Desc_SteelPipe_C
        "name": "Steel Pipe",
        "description": "Primarily used when constructing slightly more advanced buildings."
    },
    "fused-modular-frame": { // Desc_ModularFrameFused_C
        "name": "Fused Modular Frame",
        "description": "A corrosion-resistant, nitride-hardened, highly-robust-yet-lightweight modular frame."
    },
    "radio-control-unit": { // Desc_ModularFrameLightweight_C
        "name": "Radio Control Unit",
        "description": "Enhances and directs radio signals."
    },
    "ficsite-ingot": { // Desc_FicsiteIngot_C
        "name": "Ficsite Ingot",
        "description": "Produced by reconstructing other metals on a molecular level using Strange Alien Matter.<br>Synthesized by FICSIT to be the perfect construction material, and used in the most high-end processes."
    },
    "biochemical-sculptor": { // Desc_SpaceElevatorPart_10_C
        "name": "Biochemical Sculptor",
        "description": "Project Part #10. Ship via the Space Elevator to complete phases of Project Assembly.<br>Years ahead of the competition, this top-of-the-line 3D printer is used for the production of synthetic biological resources."
    },
    "assembly-director-system": { // Desc_SpaceElevatorPart_7_C
        "name": "Assembly Director System",
        "description": "Project Part #6. Ship via the Space Elevator to complete phases of Project Assembly.<br>This extremely fast and precise computing system is specifically designed to direct the Project Assembly: Assembly Phase."
    },
    "caterium-ingot": { // Desc_GoldIngot_C
        "name": "Caterium Ingot",
        "description": "Smelted from Caterium Ore. Primarily used for advanced electronics."
    },
    "empty-canister": { // Desc_FluidCanister_C
        "name": "Empty Canister",
        "description": "Used to package fluids for transportation."
    },
    "circuit-board": { // Desc_CircuitBoard_C
        "name": "Circuit Board",
        "description": "Advanced electronics that have a plethora of different uses."
    },
    "plastic": { // Desc_Plastic_C
        "name": "Plastic",
        "description": "Versatile and easy to manufacture, this material has a wide range of uses."
    },
    "encased-industrial-beam": { // Desc_SteelPlateReinforced_C
        "name": "Encased Industrial Beam",
        "description": "Simultaneously utilizes the compressive strength of concrete and the tensile strength of steel.<br>Mostly used as a stable base for constructing buildings."
    },
    "rubber": { // Desc_Rubber_C
        "name": "Rubber",
        "description": "A very flexible material that has a lot of friction."
    },
    "polymer-resin": { // Desc_PolymerResin_C
        "name": "Polymer Resin",
        "description": "A by-product of Crude Oil refinement into Fuel. Commonly used to manufacture Plastic and Rubber."
    },
    "heavy-oil-residue": { // Desc_HeavyOilResidue_C
        "name": "Heavy Oil Residue",
        "description": "A by-product of Plastic and Rubber production. Can be further refined into Fuel and Petroleum Coke."
    },
    "quartz-crystal": { // Desc_QuartzCrystal_C
        "name": "Quartz Crystal",
        "description": "Derived from Raw Quartz. Used in the production of advanced radar technology and high-quality display screens."
    },
    "steel-ingot": { // Desc_SteelIngot_C
        "name": "Steel Ingot",
        "description": "Smelted from a combination of Iron Ore and Coal. Can be made into several parts used in building construction."
    },
    "versatile-framework": { // Desc_SpaceElevatorPart_2_C
        "name": "Versatile Framework",
        "description": "Project Part #2. Ship via the Space Elevator to complete phases of Project Assembly."
    },
    "packaged-water": { // Desc_PackagedWater_C
        "name": "Packaged Water",
        "description": "Water, packaged for alternative transport."
    },
    "copper-ingot": { // Desc_CopperIngot_C
        "name": "Copper Ingot",
        "description": "Used for crafting the most basic parts."
    },
    "aluminum-scrap": { // Desc_AluminumScrap_C
        "name": "Aluminum Scrap",
        "description": "Refined from Alumina. Can be smelted into Aluminum Ingots for industrial usage."
    },
    "aluminum-casing": { // Desc_AluminumCasing_C
        "name": "Aluminum Casing",
        "description": "A versatile container cast from Aluminum Ingots."
    },
    "alumina-solution": { // Desc_AluminaSolution_C
        "name": "Alumina Solution",
        "description": "Dissolved Alumina, extracted from Bauxite. Can be further refined into Aluminum Scrap for Aluminum Ingot production."
    },
    "computer": { // Desc_Computer_C
        "name": "Computer",
        "description": "A complex logic machine that is used to control advanced behavior in other machines."
    },
    "heavy-modular-frame": { // Desc_ModularFrameHeavy_C
        "name": "Heavy Modular Frame",
        "description": "A more robust multipurpose frame."
    },
    "smart-plating": { // Desc_SpaceElevatorPart_1_C
        "name": "Smart Plating",
        "description": "Project Part #1. Ship via the Space Elevator to complete phases of Project Assembly."
    },
    "high-speed-connector": { // Desc_HighSpeedConnector_C
        "name": "High-Speed Connector",
        "description": "Connects multiple cables and wires in a very efficient way. Uses a standard pattern, so it has many varied applications."
    },
    "automated-wiring": { // Desc_SpaceElevatorPart_3_C
        "name": "Automated Wiring",
        "description": "Project Part #3. Ship via the Space Elevator to complete phases of Project Assembly."
    },
    "stator": { // Desc_Stator_C
        "name": "Stator",
        "description": "Used for crafting.<br>The static parts of a motor."
    },
    "ai-limiter": { // Desc_CircuitBoardHighSpeed_C
        "name": "AI Limiter",
        "description": "Controls AIs and keeps them from evolving in malicious ways. Super advanced electronics."
    },
    "quickwire": { // Desc_HighSpeedWire_C
        "name": "Quickwire",
        "description": "Caterium's high conductivity and resistance to corrosion make it ideal for small, advanced electronics."
    },
    "modular-engine": { // Desc_SpaceElevatorPart_4_C
        "name": "Modular Engine",
        "description": "Project Part #4. Ship via the Space Elevator to complete phases of Project Assembly."
    },
    "adaptive-control-unit": { // Desc_SpaceElevatorPart_5_C
        "name": "Adaptive Control Unit",
        "description": "Project Part #5. Ship via the Space Elevator to complete phases of Project Assembly."
    },
    "pressure-conversion-cube": { // Desc_PressureConversionCube_C
        "name": "Pressure Conversion Cube",
        "description": "Converts outgoing force into internal pressure. Required to contain unstable, high-energy matter."
    },
    "encased-plutonium-cell": { // Desc_PlutoniumCell_C
        "name": "Encased Plutonium Cell",
        "description": "Plutonium Pellets encased in concrete.<br>Used to produce Plutonium Fuel Rods for Nuclear Power production.<br>Caution: Moderately Radioactive."
    },
    "plutonium-pellet": { // Desc_PlutoniumPellet_C
        "name": "Plutonium Pellet",
        "description": "Produced in the Particle Accelerator through conversion of Non-fissile Uranium.<br>Used to produce Encased Plutonium Cells for Plutonium Fuel Rods.<br>Power Usage: 250-750 MW (500 MW average).<br>Caution: Moderately Radioactive."
    },
    "non-fissile-uranium": { // Desc_NonFissibleUranium_C
        "name": "Non-Fissile Uranium",
        "description": "The Uranium-238 isotope is non-fissile, meaning it cannot be used for nuclear fission. It can, however, be converted into fissile Plutonium in the Particle Accelerator.<br>Caution: Mildly Radioactive."
    },
    "sulfuric-acid": { // Desc_SulfuricAcid_C
        "name": "Sulfuric Acid",
        "description": "Produced by combining Sulfur and Water in a complex reaction. Primarily used in refinement processes and Battery production."
    },
    "copper-powder": { // Desc_CopperDust_C
        "name": "Copper Powder",
        "description": "Ground-up Copper Ingots.<br>The high natural density of Copper, combined with the granularity of the powder, makes this part perfect for producing Nuclear Pasta in the Particle Accelerator."
    },
    "heat-sink": { // Desc_AluminumPlateReinforced_C
        "name": "Heat Sink",
        "description": "Used to dissipate heat faster."
    },
    "electromagnetic-control-rod": { // Desc_ElectromagneticControlRod_C
        "name": "Electromagnetic Control Rod",
        "description": "Regulates power output via electromagnetism."
    },
    "nuclear-pasta": { // Desc_SpaceElevatorPart_9_C
        "name": "Nuclear Pasta",
        "description": "Project Part #9. Ship via the Space Elevator to complete phases of Project Assembly.<br>Power Usage: 500-1500 MW (1000 MW average).<br>Nuclear Pasta is extremely dense degenerate matter, formed when extreme pressure forces protons and electrons together into neutrons. It is theorized to exist naturally within the crust of neutron stars."
    },
    "encased-uranium-cell": { // Desc_UraniumCell_C
        "name": "Encased Uranium Cell",
        "description": "Used to produce Uranium Fuel Rods for Nuclear Power production. Made from Uranium Ore.<br>Caution: Mildly Radioactive."
    },
    "dissolved-silica": { // Desc_DissolvedSilica_C
        "name": "Dissolved Silica",
        "description": "Silica dissolved in Water, produced as part of the alternative refinement of Raw Quartz.<br>The Silica can be extracted from the Water to complete the refinement process."
    },
    "thermal-propulsion-rocket": { // Desc_SpaceElevatorPart_8_C
        "name": "Thermal Propulsion Rocket",
        "description": "Project Part #8. Ship via the Space Elevator to complete phases of Project Assembly.<br>Uses extreme heat to produce the high-pressure plasma required to get Project Assembly into motion."
    },
    "black-powder": { // Desc_Gunpowder_C
        "name": "Black Powder",
        "description": "An explosive powder that is commonly used to produce simple explosives."
    },
    "ficsonium": { // Desc_Ficsonium_C
        "name": "Ficsonium",
        "description": "Usage and production of this material is strictly prohibited. On Earth, that is. There are no rules in space, only efficiency. <br>Power Usage: 500-1500 MW (1000 MW average)."
    },
    "singularity-cell": { // Desc_SingularityCell_C
        "name": "Singularity Cell",
        "description": "Used to break down space and time. Required to power Portals."
    },
    "ballistic-warp-drive": { // Desc_SpaceElevatorPart_11_C
        "name": "Ballistic Warp Drive",
        "description": "Project Part #11. Ship via the Space Elevator to complete phases of Project Assembly.<br>Power Usage: 1000-2000 MW (1500 MW average).<br>A large amount of force is required for the Warp Drives to activate, so sticking them to rockets was the logical next step. Additionally, results improved immensely when the observers were further removed from the Warp Drives upon activation."
    },
    "gas-filter": { // Desc_Filter_C
        "name": "Gas Filter",
        "description": "Filters out toxins and pollutants from the air when used with a Gas Mask."
    },
    "alien-protein": { // Desc_AlienProtein_C
        "name": "Alien Protein",
        "description": "Ground-up Alien Remains in a neat little package.<br>Used for medical purposes and to research alien organisms."
    },
    "blue-power-slug": { // Desc_Crystal_C
        "name": "Blue Power Slug",
        "description": "A strange slug radiating an unknown weak power."
    },
    "alien-dna-capsule": { // Desc_AlienDNACapsule_C
        "name": "Alien DNA Capsule",
        "description": "Translates organic chemicals into readable alien genetic information.<br>Used for researching alien organisms.<br>Go the extra kilometer! Knowledge is power, and power is just efficiency with fewer steps. Depositing Alien DNA Capsules in the AWESOME Sink provides FICSIT with knowledge, and pioneers with Coupons."
    },
    "mercer-sphere": { // Desc_WAT2_C
        "name": "Mercer Sphere",
        "description": "A weird alien phenomenon. While the sphere appears liquid, it behaves like a solid and does not have any detectable mass. It seems to somehow interact with and have awareness of its environment."
    },
    "purple-power-slug": { // Desc_Crystal_mk3_C
        "name": "Purple Power Slug",
        "description": "A strange slug radiating a powerful unknown power."
    },
    "yellow-power-slug": { // Desc_Crystal_mk2_C
        "name": "Yellow Power Slug",
        "description": "A strange slug radiating an unknown power."
    },
    "smokeless-powder": { // Desc_GunpowderMK2_C
        "name": "Smokeless Powder",
        "description": "An explosive powder that is commonly used to produce modern firearms."
    },
    "ficsmas-wonder-star": { // Desc_XmasStar_C
        "name": "FICSMAS Wonder Star",
        "description": "This special FICSMAS Star signifies FICSIT's productivity all across the universe. It also signifies the fact that you have nearly completed the Holiday Event, so it's time to get back to work."
    },
    "ficsmas-ornament-bundle": { // Desc_XmasBallCluster_C
        "name": "FICSMAS Ornament Bundle",
        "description": "All the FICSMAS Ornaments smashed together to make even more FICSMAS Decorations!"
    },
    "ficsmas-decoration": { // Desc_XmasWreath_C
        "name": "FICSMAS Decoration",
        "description": "A decoration used to make decorations. Its use cases are questionable."
    },
    "candy-cane": { // Desc_CandyCane_C
        "name": "Candy Cane",
        "description": "A delicious Candy Cane to be enjoyed during the FICSMAS Holidays. <br>*Disclaimer: Not for consumption..."
    },
    "actual-snow": { // Desc_Snow_C
        "name": "Actual Snow",
        "description": "It's snow. Not the nice, thick, crunchy kind, though... more the disgustingly wet, slushy kind... Guess we can make stuff from it."
    },
    "ficsmas-bow": { // Desc_XmasBow_C
        "name": "FICSMAS Bow",
        "description": "A fancy Bow. Maybe someone could wear this? You certainly can't! What you can do is make parts and decorations from it. Probably."
    },
    "copper-ficsmas-ornament": { // Desc_XmasBall3_C
        "name": "Copper FICSMAS Ornament",
        "description": "Still used for making FICSMAS Decorations."
    },
    "iron-ficsmas-ornament": { // Desc_XmasBall4_C
        "name": "Iron FICSMAS Ornament",
        "description": "A super special- Nope! Still just used for making FICSMAS Decorations."
    },
    "ficsmas-tree-branch": { // Desc_XmasBranch_C
        "name": "FICSMAS Tree Branch",
        "description": "A special Tree Branch used to produce parts and buildings during the FICSMAS Event."
    },
    "red-ficsmas-ornament": { // Desc_XmasBall1_C
        "name": "Red FICSMAS Ornament",
        "description": "Used for making FICSMAS Decorations."
    },
    "blue-ficsmas-ornament": { // Desc_XmasBall2_C
        "name": "Blue FICSMAS Ornament",
        "description": "Again, used for making FICSMAS Decorations."
    },
    "ficsmas-gift": { // Desc_Gift_C
        "name": "FICSMAS Gift",
        "description": "Special FICSMAS buildings and parts can be obtained and produced from this FICSIT Holiday present.<br>*Watch the sky for deliveries from orbit!"
    },
    "rebar-gun": { // Desc_RebarGunProjectile_C
        "name": "Rebar Gun",
        "description": "An improvised ranged weapon for self-defense. Has to be reloaded after each use."
    },
    "rifle": { // BP_EquipmentDescriptorRifle_C
        "name": "Rifle",
        "description": "A long-range, rapid-fire weapon. Specifically designed to deliver adequate performance within the designated work area."
    },
    "uranium-fuel-rod": { // Desc_NuclearFuelRod_C
        "name": "Uranium Fuel Rod",
        "description": "Used as fuel for Nuclear Power Plants.<br>Caution: Produces radioactive Uranium Waste when consumed.<br>Caution: Moderately Radioactive."
    },
    "plutonium-fuel-rod": { // Desc_PlutoniumFuelRod_C
        "name": "Plutonium Fuel Rod",
        "description": "Used as fuel for Nuclear Power Plants.<br>Caution: Produces radioactive Plutonium Waste when consumed.<br>Caution: HIGHLY Radioactive."
    },
    "ficsonium-fuel-rod": { // Desc_FicsoniumFuelRod_C
        "name": "Ficsonium Fuel Rod",
        "description": "Used as fuel for Nuclear Power Plants.<br>The power source that put FICSIT on the map. Literally. The crater is still there.<br>Caution: Moderately Radioactive."
    },
    "explosive-rebar": { // Desc_Rebar_Explosive_C
        "name": "Explosive Rebar",
        "description": "Explodes on impact, dealing heavy damage."
    },
    "stun-rebar": { // Desc_Rebar_Stunshot_C
        "name": "Stun Rebar",
        "description": "Electrocutes the target on impact, stunning it for a short time.<br>Stun Duration: 5 seconds"
    },
    "homing-rifle-ammo": { // Desc_CartridgeSmartProjectile_C
        "name": "Homing Rifle Ammo",
        "description": "The bullet guidance system built into this ammunition allows it to accurately hit any target within the reticle area.<br>Especially useful when dealing with agile threats, or for pioneers who can't be bothered to aim properly."
    },
    "cluster-nobelisk": { // Desc_NobeliskCluster_C
        "name": "Cluster Nobelisk",
        "description": "Detonates into multiple smaller explosions. Practical for clearing out large areas of vegetation and other inconveniences."
    },
    "nobelisk": { // Desc_NobeliskExplosive_C
        "name": "Nobelisk",
        "description": "A simple explosive, useful for clearing boulders, vegetation, and other obstacles."
    },
    "gas-nobelisk": { // Desc_NobeliskGas_C
        "name": "Gas Nobelisk",
        "description": "Creates a deadly gas cloud instead of a regular explosion."
    },
    "nuke-nobelisk": { // Desc_NobeliskNuke_C
        "name": "Nuke Nobelisk",
        "description": "Uses a nuclear fission reaction to generate a massive explosion.<br>WARNING: Ensure all FICSIT property is clear of the blast zone before detonation."
    },
    "pulse-nobelisk": { // Desc_NobeliskShockwave_C
        "name": "Pulse Nobelisk",
        "description": "Generates a powerful shockwave instead of a regular explosion."
    },
    "sweet-fireworks": { // Desc_Fireworks_Projectile_01_C
        "name": "Sweet Fireworks",
        "description": "Merry FICSMAS and a Happy New Year!"
    },
    "fancy-fireworks": { // Desc_Fireworks_Projectile_02_C
        "name": "Fancy Fireworks",
        "description": "Fireworks are produced from random ingredients. Primarily used for having a good time."
    },
    "sparkly-fireworks": { // Desc_Fireworks_Projectile_03_C
        "name": "Sparkly Fireworks",
        "description": "Goes Pfffeeeeew... BOOM! *Sparkle*"
    },
    "snowball": { // Desc_SnowballProjectile_C
        "name": "Snowball",
        "description": "Compressed dihydrogen monoxide crystals."
    },
    "iron-rebar": { // Desc_SpikedRebar_C
        "name": "Iron Rebar",
        "description": "Can be shot using the Rebar Gun for self-defense purposes."
    },
    "hazmat-suit": { // BP_EquipmentDescriptorHazmatSuit_C
        "name": "Hazmat Suit",
        "description": "Shields pioneers from the adverse effects of radiation. <br>Consumes Iodine-Infused Filters from the pioneer's inventory when worn in radioactive areas."
    },
    "nobelisk-detonator": { // BP_EquipmentDescriptorNobeliskDetonator_C
        "name": "Nobelisk Detonator",
        "description": "A remote-control device used to handle and detonate Nobelisks."
    },
    "factory-cart™": { // Desc_GolfCart_C
        "name": "Factory Cart™",
        "description": "The one and only FICSIT Factory Cart™.<br>Now with special FICSIT-Foundation-only Grip Wheels, for an even smoother and faster factory floor experience!"
    },
    "golden-factory-cart™": { // Desc_GolfCartGold_C
        "name": "Golden Factory Cart™",
        "description": "The one and only Golden FICSIT Factory Cart™<br>You have now officially ascended. <br>Go forth now, Master of Spaghetti, God of the Factory, Sinker of Cups, Employee of the Planet... travel in STYLE!"
    },
    "portable-miner": { // BP_ItemDescriptorPortableMiner_C
        "name": "Portable Miner",
        "description": "Automatically extracts a resource when placed on a resource node.<br>Note: Has limited storage space."
    },
    "xeno-zapper": { // BP_EquipmentDescriptorShockShank_C
        "name": "Xeno-Zapper",
        "description": "A standard issue self-defense electroshock melee weapon."
    },
    "object-scanner": { // BP_EquipmentDescriptorObjectScanner_C
        "name": "Object Scanner",
        "description": "Scans the area for a selected item. Beeps at a rate proportional to proximity and direction."
    },
    "hoverpack": { // BP_EquipmentDescriptorHoverPack_C
        "name": "Hoverpack",
        "description": "Power Consumption: 100 MW<br>Allows pioneers to move vertically and hover in mid-air to improve building efficiency and factory traversal. Wirelessly connects to nearby power connections, such as Power Poles and Buildings, for power consumption.<br>Slow-Fall: Hold {PlayerMovement_Jump} after losing connection mid-air.<br>Disable Hoverpack: Double tap {PlayerMovement_Crouch} while hovering."
    },
    "jetpack": { // BP_EquipmentDescriptorJetPack_C
        "name": "Jetpack",
        "description": "Allows pioneers to travel through the air with increased control.<br>Fuel is automatically consumed from the pioneer's inventory to refill the Jetpack while on the ground.<br>Different fuel types can be used and provide different levels of Jetpack efficiency. The preferred fuel type will be used if available, and can be set in the equipment inventory."
    },
    "xeno-basher": { // BP_EquipmentDescriptorStunSpear_C
        "name": "Xeno-Basher",
        "description": "A heavy self-defense electroshock melee weapon."
    },
    "chainsaw": { // Desc_Chainsaw_C
        "name": "Chainsaw",
        "description": "Clears an area of flora that is too difficult to remove by hand.<br>Fuel: Biofuel"
    },
    "blade-runners": { // BP_EquipmentDescriptorJumpingStilts_C
        "name": "Blade Runners",
        "description": "An exoskeleton for the lower legs that assists movement, allowing pioneers to sprint faster and jump higher.<br>Also dampens the impact of landing."
    },
    "zipline": { // BP_EqDescZipLine_C
        "name": "Zipline",
        "description": "Provides faster traversal of factories by allowing pioneers to zip along Power lines.<br>Activate the Zipline and aim at a nearby Power Line to connect to it."
    },
    "gas-mask": { // BP_EquipmentDescriptorGasmask_C
        "name": "Gas Mask",
        "description": "Allows pioneers to breathe normally in toxic gas-filled areas.<br>Consumes Gas Filters from the pioneer's inventory when in use."
    },
    "candy-cane-basher": { // BP_EquipmentDescriptorCandyCane_C
        "name": "Candy Cane Basher",
        "description": "A heavy, delicious self-defense weapon for use at melee range."
    },
    "shatter-rebar": { // Desc_Rebar_Spreadshot_C
        "name": "Shatter Rebar",
        "description": "Fractures when shot, launching deadly debris with wide spread but limited range."
    },
    "turbo-rifle-ammo": { // Desc_CartridgeChaos_C
        "name": "Turbo Rifle Ammo",
        "description": "Lightweight, compact, and volatile. These rounds provide extreme capacity and rate of fire at the cost of accuracy."
    },
    "rifle-ammo": { // Desc_CartridgeStandard_C
        "name": "Rifle Ammo",
        "description": "Standard issue Rifle ammunition, useful for establishing dominance."
    },
    "iron-ore": { // Desc_OreIron_C
        "name": "Iron Ore",
        "description": "Used for crafting.<br>The most essential basic resource."
    },
    "coal": { // Desc_Coal_C
        "name": "Coal",
        "description": "Mainly used as fuel for vehicles & Coal-Powered Generators, or in Steel production."
    },
    "water": { // Desc_Water_C
        "name": "Water",
        "description": "It's water."
    },
    "nitrogen-gas": { // Desc_NitrogenGas_C
        "name": "Nitrogen Gas",
        "description": "Has a variety of uses, including metallurgy, cooling, and Nitric Acid production. On MASSAGE-2 (AB)b, it can be extracted from underground gas wells."
    },
    "sulfur": { // Desc_Sulfur_C
        "name": "Sulfur",
        "description": "Primarily used to produce Black Powder."
    },
    "sam": { // Desc_SAM_C
        "name": "SAM",
        "description": "Strange Alien Matter, commonly referred to as SAM, doesn't seem to follow the known laws of physics. It whispers of new possibilities."
    },
    "bauxite": { // Desc_OreBauxite_C
        "name": "Bauxite",
        "description": "Used to produce Alumina, which can be further refined into the Aluminum Scrap required to produce Aluminum Ingots."
    },
    "caterium-ore": { // Desc_OreGold_C
        "name": "Caterium Ore",
        "description": "Smelted into Caterium Ingots, which are primarily used for advanced electronics."
    },
    "copper-ore": { // Desc_OreCopper_C
        "name": "Copper Ore",
        "description": "Used for crafting.<br>A basic resource primarily used for electricity."
    },
    "raw-quartz": { // Desc_RawQuartz_C
        "name": "Raw Quartz",
        "description": "Can be processed into Quartz Crystals and Silica, which both offer a variety of applications."
    },
    "limestone": { // Desc_Stone_C
        "name": "Limestone",
        "description": "Used for crafting.<br>A basic resource primarily used for stable Foundations."
    },
    "uranium": { // Desc_OreUranium_C
        "name": "Uranium",
        "description": "A radioactive element. <br>Used to produce Encased Uranium Cells for Uranium Fuel Rods.<br>Caution: Moderately Radioactive."
    },
    "crude-oil": { // Desc_LiquidOil_C
        "name": "Crude Oil",
        "description": "Refined into all kinds of Oil-based resources, like Fuel and Plastic."
    },
    "medicinal-inhaler": { // Desc_Medkit_C
        "name": "Medicinal Inhaler",
        "description": "Fully restores health when used.<br>The FICSIT Medicinal Inhaler can be produced from a variety of different ingredients."
    },
    "solid-biofuel": { // Desc_Biofuel_C
        "name": "Solid Biofuel",
        "description": "The most energy-efficient form of solid Biomass. Can be used as fuel for the Chainsaw."
    },
    "packaged-liquid-biofuel": { // Desc_PackagedBiofuel_C
        "name": "Packaged Liquid Biofuel",
        "description": "Liquid Biofuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack."
    },
    "biomass": { // Desc_GenericBiomass_C
        "name": "Biomass",
        "description": "Primarily used as fuel.<br>Biomass Burners and vehicles can use it for power.<br>Biomass is much more energy-efficient than raw biological matter."
    },
    "leaves": { // Desc_Leaves_C
        "name": "Leaves",
        "description": "Primarily used as fuel.<br>Biomass Burners and vehicles can use Leaves for power."
    },
    "mycelia": { // Desc_Mycelia_C
        "name": "Mycelia",
        "description": "Used for crafting.<br>Biomass Burners and vehicles can also use Mycelia for power."
    },
    "wood": { // Desc_Wood_C
        "name": "Wood",
        "description": "Primarily used as fuel.<br>Biomass Burners and vehicles can use Wood for power."
    },
    "liquid-biofuel": { // Desc_LiquidBiofuel_C
        "name": "Liquid Biofuel",
        "description": "Liquid Biofuel can be used as-is to generate power, or packaged to be used as fuel for vehicles."
    },
    "packaged-alumina-solution": { // Desc_PackagedAlumina_C
        "name": "Packaged Alumina Solution",
        "description": "Alumina Solution, packaged for alternative transport."
    },
    "packaged-nitrogen-gas": { // Desc_PackagedNitrogenGas_C
        "name": "Packaged Nitrogen Gas",
        "description": "Nitrogen Gas, packaged for alternative transport."
    },
    "packaged-nitric-acid": { // Desc_PackagedNitricAcid_C
        "name": "Packaged Nitric Acid",
        "description": "Nitric Acid, packaged for alternative transport."
    },
    "packaged-sulfuric-acid": { // Desc_PackagedSulfuricAcid_C
        "name": "Packaged Sulfuric Acid",
        "description": "Sulfuric Acid, packaged for alternative transport."
    },
    "fabric": { // Desc_Fabric_C
        "name": "Fabric",
        "description": "Used to craft equipment.<br>Flexible but durable fabric."
    },
    "hog-remains": { // Desc_HogParts_C
        "name": "Hog Remains",
        "description": "The carapace of an alien Hog creature.<br>Used for MAM research."
    },
    "spitter-remains": { // Desc_SpitterParts_C
        "name": "Spitter Remains",
        "description": "The remains of a plasma-spitting alien creature.<br>Used for MAM research."
    },
    "stinger-remains": { // Desc_StingerParts_C
        "name": "Stinger Remains",
        "description": "The remains of whatever that creepy thing was.<br>Used for MAM research."
    },
    "hatcher-remains": { // Desc_HatcherParts_C
        "name": "Hatcher Remains",
        "description": "The shell-like remains of an alien... thing.<br>Used for MAM research."
    },
    "power-shard": { // Desc_CrystalShard_C
        "name": "Power Shard",
        "description": "Power Slug mucus compressed into a solid crystal-like shard. <br>It radiates a strange power."
    },
    "somersloop": { // Desc_WAT1_C
        "name": "Somersloop",
        "description": "An odd alien object with a mind-bending, yet somehow familiar shape. It emits an unsettling energy."
    },
    "paleberry": { // Desc_Berry_C
        "name": "Paleberry",
        "description": "Consumable<br>Eat to restore 1 health segment."
    },
    "beryl-nut": { // Desc_Nut_C
        "name": "Beryl Nut",
        "description": "Consumable<br>Eat to restore half a health segment."
    },
    "bacon-agaric": { // Desc_Shroom_C
        "name": "Bacon Agaric",
        "description": "Consumable<br>Eat to restore 2 health segments."
    },
    "parachute": { // Desc_Parachute_C
        "name": "Parachute",
        "description": "Slows down your fall when activated in mid-air."
    },
    "alien-power-matrix": { // Desc_AlienPowerFuel_C
        "name": "Alien Power Matrix",
        "description": "This intricate condensed-matter matrix is used to enhance the output of the Alien Power Augmenter. <br>Initially developed in efforts to create a human-made Somersloop, the Alien Power Matrix cannot sustain the extra-dimensional energy connection on its own. However, it can effectively stabilize the energy stream of the Somersloop."
    },
} as const satisfies Record<string, Item>;
