// This file is generated by 'data/gen.ts'!
//
// The data in this file is not licensed under the same license as the rest of the
// project. It is derived from the Satisfactory Wiki, which in turn took it from the
// game. See the main README for more information.


use super::ItemKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Deserialize, serde::Serialize)]
#[repr(u16)]
pub enum RecipeKind {
    #[serde(rename = "nuclear-waste")]
    NuclearWaste = 0,
    #[serde(rename = "plutonium-waste")]
    PlutoniumWaste = 1,
    #[serde(rename = "iron-plate")]
    IronPlate = 2,
    #[serde(rename = "iron-rod")]
    IronRod = 3,
    #[serde(rename = "iron-ingot")]
    IronIngot = 4,
    #[serde(rename = "nitro-rocket-fuel")]
    NitroRocketFuel = 5,
    #[serde(rename = "rocket-fuel")]
    RocketFuel = 6,
    #[serde(rename = "packaged-rocket-fuel")]
    PackagedRocketFuel = 7,
    #[serde(rename = "unpackage-rocket-fuel")]
    UnpackageRocketFuel = 8,
    #[serde(rename = "dark-ion-fuel")]
    DarkIonFuel = 9,
    #[serde(rename = "dark-matter-residue")]
    DarkMatterResidue = 10,
    #[serde(rename = "excited-photonic-matter")]
    ExcitedPhotonicMatter = 11,
    #[serde(rename = "dark-matter-crystal")]
    DarkMatterCrystal = 12,
    #[serde(rename = "superposition-oscillator")]
    SuperpositionOscillator = 13,
    #[serde(rename = "neural-quantum-processor")]
    NeuralQuantumProcessor = 14,
    #[serde(rename = "ai-expansion-server")]
    AiExpansionServer = 15,
    #[serde(rename = "ionized-fuel")]
    IonizedFuel = 16,
    #[serde(rename = "packaged-ionized-fuel")]
    PackagedIonizedFuel = 17,
    #[serde(rename = "unpackage-ionized-fuel")]
    UnpackageIonizedFuel = 18,
    #[serde(rename = "turbo-diamonds")]
    TurboDiamonds = 19,
    #[serde(rename = "sam-fluctuator")]
    SamFluctuator = 20,
    #[serde(rename = "ficsite-trigon")]
    FicsiteTrigon = 21,
    #[serde(rename = "ficsite-ingot-iron")]
    FicsiteIngotIron = 22,
    #[serde(rename = "time-crystal")]
    TimeCrystal = 23,
    #[serde(rename = "diamonds")]
    Diamonds = 24,
    #[serde(rename = "reanimated-sam")]
    ReanimatedSam = 25,
    #[serde(rename = "biochemical-sculptor")]
    BiochemicalSculptor = 26,
    #[serde(rename = "ficsite-ingot-aluminum")]
    FicsiteIngotAluminum = 27,
    #[serde(rename = "ficsite-ingot-caterium")]
    FicsiteIngotCaterium = 28,
    #[serde(rename = "bauxite-caterium")]
    BauxiteCaterium = 29,
    #[serde(rename = "bauxite-copper")]
    BauxiteCopper = 30,
    #[serde(rename = "caterium-ore-copper")]
    CateriumOreCopper = 31,
    #[serde(rename = "caterium-ore-quartz")]
    CateriumOreQuartz = 32,
    #[serde(rename = "coal-iron")]
    CoalIron = 33,
    #[serde(rename = "coal-limestone")]
    CoalLimestone = 34,
    #[serde(rename = "copper-ore-quartz")]
    CopperOreQuartz = 35,
    #[serde(rename = "copper-ore-sulfur")]
    CopperOreSulfur = 36,
    #[serde(rename = "iron-ore-limestone")]
    IronOreLimestone = 37,
    #[serde(rename = "limestone-sulfur")]
    LimestoneSulfur = 38,
    #[serde(rename = "nitrogen-gas-bauxite")]
    NitrogenGasBauxite = 39,
    #[serde(rename = "nitrogen-gas-caterium")]
    NitrogenGasCaterium = 40,
    #[serde(rename = "raw-quartz-bauxite")]
    RawQuartzBauxite = 41,
    #[serde(rename = "raw-quartz-coal")]
    RawQuartzCoal = 42,
    #[serde(rename = "sulfur-coal")]
    SulfurCoal = 43,
    #[serde(rename = "sulfur-iron")]
    SulfurIron = 44,
    #[serde(rename = "uranium-ore-bauxite")]
    UraniumOreBauxite = 45,
    #[serde(rename = "turbofuel")]
    Turbofuel = 46,
    #[serde(rename = "packaged-turbofuel")]
    PackagedTurbofuel = 47,
    #[serde(rename = "unpackage-turbofuel")]
    UnpackageTurbofuel = 48,
    #[serde(rename = "charcoal")]
    Charcoal = 49,
    #[serde(rename = "biocoal")]
    Biocoal = 50,
    #[serde(rename = "compacted-coal")]
    CompactedCoal = 51,
    #[serde(rename = "circuit-board")]
    CircuitBoard = 52,
    #[serde(rename = "fuel")]
    Fuel = 53,
    #[serde(rename = "petroleum-coke")]
    PetroleumCoke = 54,
    #[serde(rename = "plastic")]
    Plastic = 55,
    #[serde(rename = "rubber")]
    Rubber = 56,
    #[serde(rename = "residual-fuel")]
    ResidualFuel = 57,
    #[serde(rename = "residual-plastic")]
    ResidualPlastic = 58,
    #[serde(rename = "residual-rubber")]
    ResidualRubber = 59,
    #[serde(rename = "pink-diamonds")]
    PinkDiamonds = 60,
    #[serde(rename = "petroleum-diamonds")]
    PetroleumDiamonds = 61,
    #[serde(rename = "oil-based-diamonds")]
    OilBasedDiamonds = 62,
    #[serde(rename = "cloudy-diamonds")]
    CloudyDiamonds = 63,
    #[serde(rename = "dark-matter-trap")]
    DarkMatterTrap = 64,
    #[serde(rename = "dark-matter-crystallization")]
    DarkMatterCrystallization = 65,
    #[serde(rename = "wet-concrete")]
    WetConcrete = 66,
    #[serde(rename = "turbo-heavy-fuel")]
    TurboHeavyFuel = 67,
    #[serde(rename = "steel-rod")]
    SteelRod = 68,
    #[serde(rename = "steel-beam")]
    SteelBeam = 69,
    #[serde(rename = "steel-pipe")]
    SteelPipe = 70,
    #[serde(rename = "steel-ingot")]
    SteelIngot = 71,
    #[serde(rename = "versatile-framework")]
    VersatileFramework = 72,
    #[serde(rename = "steel-canister")]
    SteelCanister = 73,
    #[serde(rename = "empty-canister")]
    EmptyCanister = 74,
    #[serde(rename = "packaged-fuel")]
    PackagedFuel = 75,
    #[serde(rename = "liquid-biofuel")]
    LiquidBiofuel = 76,
    #[serde(rename = "packaged-liquid-biofuel")]
    PackagedLiquidBiofuel = 77,
    #[serde(rename = "packaged-oil")]
    PackagedOil = 78,
    #[serde(rename = "packaged-heavy-oil-residue")]
    PackagedHeavyOilResidue = 79,
    #[serde(rename = "packaged-water")]
    PackagedWater = 80,
    #[serde(rename = "unpackage-liquid-biofuel")]
    UnpackageLiquidBiofuel = 81,
    #[serde(rename = "unpackage-fuel")]
    UnpackageFuel = 82,
    #[serde(rename = "unpackage-oil")]
    UnpackageOil = 83,
    #[serde(rename = "unpackage-heavy-oil-residue")]
    UnpackageHeavyOilResidue = 84,
    #[serde(rename = "unpackage-water")]
    UnpackageWater = 85,
    #[serde(rename = "steamed-copper-sheet")]
    SteamedCopperSheet = 86,
    #[serde(rename = "rubber-concrete")]
    RubberConcrete = 87,
    #[serde(rename = "recycled-rubber")]
    RecycledRubber = 88,
    #[serde(rename = "pure-quartz-crystal")]
    PureQuartzCrystal = 89,
    #[serde(rename = "quartz-crystal")]
    QuartzCrystal = 90,
    #[serde(rename = "pure-iron-ingot")]
    PureIronIngot = 91,
    #[serde(rename = "pure-copper-ingot")]
    PureCopperIngot = 92,
    #[serde(rename = "pure-caterium-ingot")]
    PureCateriumIngot = 93,
    #[serde(rename = "pure-aluminum-ingot")]
    PureAluminumIngot = 94,
    #[serde(rename = "aluminum-casing")]
    AluminumCasing = 95,
    #[serde(rename = "alclad-aluminum-sheet")]
    AlcladAluminumSheet = 96,
    #[serde(rename = "alumina-solution")]
    AluminaSolution = 97,
    #[serde(rename = "aluminum-scrap")]
    AluminumScrap = 98,
    #[serde(rename = "packaged-alumina-solution")]
    PackagedAluminaSolution = 99,
    #[serde(rename = "aluminum-ingot")]
    AluminumIngot = 100,
    #[serde(rename = "silica")]
    Silica = 101,
    #[serde(rename = "crystal-oscillator")]
    CrystalOscillator = 102,
    #[serde(rename = "unpackage-alumina-solution")]
    UnpackageAluminaSolution = 103,
    #[serde(rename = "polymer-resin")]
    PolymerResin = 104,
    #[serde(rename = "plastic-smart-plating")]
    PlasticSmartPlating = 105,
    #[serde(rename = "automated-speed-wiring")]
    AutomatedSpeedWiring = 106,
    #[serde(rename = "encased-industrial-beam")]
    EncasedIndustrialBeam = 107,
    #[serde(rename = "motor")]
    Motor = 108,
    #[serde(rename = "stator")]
    Stator = 109,
    #[serde(rename = "automated-wiring")]
    AutomatedWiring = 110,
    #[serde(rename = "ai-limiter")]
    AiLimiter = 111,
    #[serde(rename = "heavy-oil-residue")]
    HeavyOilResidue = 112,
    #[serde(rename = "heavy-flexible-frame")]
    HeavyFlexibleFrame = 113,
    #[serde(rename = "computer")]
    Computer = 114,
    #[serde(rename = "heavy-modular-frame")]
    HeavyModularFrame = 115,
    #[serde(rename = "modular-engine")]
    ModularEngine = 116,
    #[serde(rename = "adaptive-control-unit")]
    AdaptiveControlUnit = 117,
    #[serde(rename = "fused-wire")]
    FusedWire = 118,
    #[serde(rename = "flexible-framework")]
    FlexibleFramework = 119,
    #[serde(rename = "electrode-circuit-board")]
    ElectrodeCircuitBoard = 120,
    #[serde(rename = "electrode-aluminum-scrap")]
    ElectrodeAluminumScrap = 121,
    #[serde(rename = "diluted-packaged-fuel")]
    DilutedPackagedFuel = 122,
    #[serde(rename = "copper-rotor")]
    CopperRotor = 123,
    #[serde(rename = "modular-frame")]
    ModularFrame = 124,
    #[serde(rename = "rotor")]
    Rotor = 125,
    #[serde(rename = "copper-sheet")]
    CopperSheet = 126,
    #[serde(rename = "smart-plating")]
    SmartPlating = 127,
    #[serde(rename = "copper-alloy-ingot")]
    CopperAlloyIngot = 128,
    #[serde(rename = "coke-steel-ingot")]
    CokeSteelIngot = 129,
    #[serde(rename = "coated-iron-plate")]
    CoatedIronPlate = 130,
    #[serde(rename = "coated-iron-canister")]
    CoatedIronCanister = 131,
    #[serde(rename = "coated-cable")]
    CoatedCable = 132,
    #[serde(rename = "bolted-frame")]
    BoltedFrame = 133,
    #[serde(rename = "adhered-iron-plate")]
    AdheredIronPlate = 134,
    #[serde(rename = "turbo-pressure-motor")]
    TurboPressureMotor = 135,
    #[serde(rename = "encased-plutonium-cell")]
    EncasedPlutoniumCell = 136,
    #[serde(rename = "pressure-conversion-cube")]
    PressureConversionCube = 137,
    #[serde(rename = "nitric-acid")]
    NitricAcid = 138,
    #[serde(rename = "non-fissile-uranium")]
    NonFissileUranium = 139,
    #[serde(rename = "copper-powder")]
    CopperPowder = 140,
    #[serde(rename = "plutonium-pellet")]
    PlutoniumPellet = 141,
    #[serde(rename = "plutonium-fuel-rod")]
    PlutoniumFuelRod = 142,
    #[serde(rename = "packaged-nitric-acid")]
    PackagedNitricAcid = 143,
    #[serde(rename = "nuclear-pasta")]
    NuclearPasta = 144,
    #[serde(rename = "unpackage-nitric-acid")]
    UnpackageNitricAcid = 145,
    #[serde(rename = "turbo-blend-fuel")]
    TurboBlendFuel = 146,
    #[serde(rename = "encased-uranium-cell")]
    EncasedUraniumCell = 147,
    #[serde(rename = "cooling-system")]
    CoolingSystem = 148,
    #[serde(rename = "battery")]
    Battery = 149,
    #[serde(rename = "supercomputer")]
    Supercomputer = 150,
    #[serde(rename = "radio-control-unit")]
    RadioControlUnit = 151,
    #[serde(rename = "sulfuric-acid")]
    SulfuricAcid = 152,
    #[serde(rename = "packaged-sulfuric-acid")]
    PackagedSulfuricAcid = 153,
    #[serde(rename = "assembly-director-system")]
    AssemblyDirectorSystem = 154,
    #[serde(rename = "high-speed-connector")]
    HighSpeedConnector = 155,
    #[serde(rename = "unpackage-sulfuric-acid")]
    UnpackageSulfuricAcid = 156,
    #[serde(rename = "super-state-computer")]
    SuperStateComputer = 157,
    #[serde(rename = "electromagnetic-control-rod")]
    ElectromagneticControlRod = 158,
    #[serde(rename = "uranium-fuel-rod")]
    UraniumFuelRod = 159,
    #[serde(rename = "magnetic-field-generator")]
    MagneticFieldGenerator = 160,
    #[serde(rename = "sloppy-alumina")]
    SloppyAlumina = 161,
    #[serde(rename = "radio-control-system")]
    RadioControlSystem = 162,
    #[serde(rename = "plutonium-fuel-unit")]
    PlutoniumFuelUnit = 163,
    #[serde(rename = "oc-supercomputer")]
    OcSupercomputer = 164,
    #[serde(rename = "heat-sink")]
    HeatSink = 165,
    #[serde(rename = "fused-modular-frame")]
    FusedModularFrame = 166,
    #[serde(rename = "empty-fluid-tank")]
    EmptyFluidTank = 167,
    #[serde(rename = "packaged-nitrogen-gas")]
    PackagedNitrogenGas = 168,
    #[serde(rename = "unpackage-nitrogen-gas")]
    UnpackageNitrogenGas = 169,
    #[serde(rename = "instant-scrap")]
    InstantScrap = 170,
    #[serde(rename = "instant-plutonium-cell")]
    InstantPlutoniumCell = 171,
    #[serde(rename = "heat-fused-frame")]
    HeatFusedFrame = 172,
    #[serde(rename = "fertile-uranium")]
    FertileUranium = 173,
    #[serde(rename = "electric-motor")]
    ElectricMotor = 174,
    #[serde(rename = "diluted-fuel")]
    DilutedFuel = 175,
    #[serde(rename = "cooling-device")]
    CoolingDevice = 176,
    #[serde(rename = "classic-battery")]
    ClassicBattery = 177,
    #[serde(rename = "automated-miner")]
    AutomatedMiner = 178,
    #[serde(rename = "alclad-casing")]
    AlcladCasing = 179,
    #[serde(rename = "molded-steel-pipe")]
    MoldedSteelPipe = 180,
    #[serde(rename = "iron-pipe")]
    IronPipe = 181,
    #[serde(rename = "steel-cast-plate")]
    SteelCastPlate = 182,
    #[serde(rename = "molded-beam")]
    MoldedBeam = 183,
    #[serde(rename = "aluminum-beam")]
    AluminumBeam = 184,
    #[serde(rename = "aluminum-rod")]
    AluminumRod = 185,
    #[serde(rename = "plastic-ai-limiter")]
    PlasticAiLimiter = 186,
    #[serde(rename = "distilled-silica")]
    DistilledSilica = 187,
    #[serde(rename = "quartz-purification")]
    QuartzPurification = 188,
    #[serde(rename = "fused-quartz-crystal")]
    FusedQuartzCrystal = 189,
    #[serde(rename = "leached-iron-ingot")]
    LeachedIronIngot = 190,
    #[serde(rename = "basic-iron-ingot")]
    BasicIronIngot = 191,
    #[serde(rename = "tempered-copper-ingot")]
    TemperedCopperIngot = 192,
    #[serde(rename = "leached-copper-ingot")]
    LeachedCopperIngot = 193,
    #[serde(rename = "tempered-caterium-ingot")]
    TemperedCateriumIngot = 194,
    #[serde(rename = "leached-caterium-ingot")]
    LeachedCateriumIngot = 195,
    #[serde(rename = "caterium-wire")]
    CateriumWire = 196,
    #[serde(rename = "iron-wire")]
    IronWire = 197,
    #[serde(rename = "infused-uranium-cell")]
    InfusedUraniumCell = 198,
    #[serde(rename = "caterium-ingot")]
    CateriumIngot = 199,
    #[serde(rename = "turbo-electric-motor")]
    TurboElectricMotor = 200,
    #[serde(rename = "turbo-motor")]
    TurboMotor = 201,
    #[serde(rename = "thermal-propulsion-rocket")]
    ThermalPropulsionRocket = 202,
    #[serde(rename = "quickwire-stator")]
    QuickwireStator = 203,
    #[serde(rename = "cheap-silica")]
    CheapSilica = 204,
    #[serde(rename = "steel-screw")]
    SteelScrew = 205,
    #[serde(rename = "cast-screw")]
    CastScrew = 206,
    #[serde(rename = "steel-rotor")]
    SteelRotor = 207,
    #[serde(rename = "encased-industrial-pipe")]
    EncasedIndustrialPipe = 208,
    #[serde(rename = "stitched-iron-plate")]
    StitchedIronPlate = 209,
    #[serde(rename = "bolted-iron-plate")]
    BoltedIronPlate = 210,
    #[serde(rename = "radio-connection-unit")]
    RadioConnectionUnit = 211,
    #[serde(rename = "fused-quickwire")]
    FusedQuickwire = 212,
    #[serde(rename = "recycled-plastic")]
    RecycledPlastic = 213,
    #[serde(rename = "uranium-fuel-unit")]
    UraniumFuelUnit = 214,
    #[serde(rename = "rigor-motor")]
    RigorMotor = 215,
    #[serde(rename = "steeled-frame")]
    SteeledFrame = 216,
    #[serde(rename = "compacted-steel-ingot")]
    CompactedSteelIngot = 217,
    #[serde(rename = "solid-steel-ingot")]
    SolidSteelIngot = 218,
    #[serde(rename = "iron-alloy-ingot")]
    IronAlloyIngot = 219,
    #[serde(rename = "silicon-high-speed-connector")]
    SiliconHighSpeedConnector = 220,
    #[serde(rename = "heavy-encased-frame")]
    HeavyEncasedFrame = 221,
    #[serde(rename = "heat-exchanger")]
    HeatExchanger = 222,
    #[serde(rename = "fine-black-powder")]
    FineBlackPowder = 223,
    #[serde(rename = "electromagnetic-connection-rod")]
    ElectromagneticConnectionRod = 224,
    #[serde(rename = "insulated-crystal-oscillator")]
    InsulatedCrystalOscillator = 225,
    #[serde(rename = "fine-concrete")]
    FineConcrete = 226,
    #[serde(rename = "crystal-computer")]
    CrystalComputer = 227,
    #[serde(rename = "caterium-computer")]
    CateriumComputer = 228,
    #[serde(rename = "caterium-circuit-board")]
    CateriumCircuitBoard = 229,
    #[serde(rename = "silicon-circuit-board")]
    SiliconCircuitBoard = 230,
    #[serde(rename = "quickwire-cable")]
    QuickwireCable = 231,
    #[serde(rename = "insulated-cable")]
    InsulatedCable = 232,
    #[serde(rename = "ficsonium")]
    Ficsonium = 233,
    #[serde(rename = "ficsonium-fuel-rod")]
    FicsoniumFuelRod = 234,
    #[serde(rename = "singularity-cell")]
    SingularityCell = 235,
    #[serde(rename = "ballistic-warp-drive")]
    BallisticWarpDrive = 236,
    #[serde(rename = "iodine-infused-filter")]
    IodineInfusedFilter = 237,
    #[serde(rename = "quickwire")]
    Quickwire = 238,
    #[serde(rename = "solid-biofuel")]
    SolidBiofuel = 239,
    #[serde(rename = "hog-protein")]
    HogProtein = 240,
    #[serde(rename = "spitter-protein")]
    SpitterProtein = 241,
    #[serde(rename = "biomass-mycelia")]
    BiomassMycelia = 242,
    #[serde(rename = "power-shard-1")]
    PowerShard1 = 243,
    #[serde(rename = "black-powder")]
    BlackPowder = 244,
    #[serde(rename = "alien-power-matrix")]
    AlienPowerMatrix = 245,
    #[serde(rename = "stinger-protein")]
    StingerProtein = 246,
    #[serde(rename = "hatcher-protein")]
    HatcherProtein = 247,
    #[serde(rename = "alien-dna-capsule")]
    AlienDnaCapsule = 248,
    #[serde(rename = "biomass-alien-protein")]
    BiomassAlienProtein = 249,
    #[serde(rename = "iron-rebar")]
    IronRebar = 250,
    #[serde(rename = "homing-rifle-ammo")]
    HomingRifleAmmo = 251,
    #[serde(rename = "stun-rebar")]
    StunRebar = 252,
    #[serde(rename = "gas-filter")]
    GasFilter = 253,
    #[serde(rename = "gas-nobelisk")]
    GasNobelisk = 254,
    #[serde(rename = "polyester-fabric")]
    PolyesterFabric = 255,
    #[serde(rename = "fabric")]
    Fabric = 256,
    #[serde(rename = "synthetic-power-shard")]
    SyntheticPowerShard = 257,
    #[serde(rename = "power-shard-5")]
    PowerShard5 = 258,
    #[serde(rename = "power-shard-2")]
    PowerShard2 = 259,
    #[serde(rename = "pulse-nobelisk")]
    PulseNobelisk = 260,
    #[serde(rename = "shatter-rebar")]
    ShatterRebar = 261,
    #[serde(rename = "turbo-rifle-ammo-packaged")]
    TurboRifleAmmoPackaged = 262,
    #[serde(rename = "turbo-rifle-ammo")]
    TurboRifleAmmo = 263,
    #[serde(rename = "nuke-nobelisk")]
    NukeNobelisk = 264,
    #[serde(rename = "rifle-ammo")]
    RifleAmmo = 265,
    #[serde(rename = "explosive-rebar")]
    ExplosiveRebar = 266,
    #[serde(rename = "cluster-nobelisk")]
    ClusterNobelisk = 267,
    #[serde(rename = "nobelisk")]
    Nobelisk = 268,
    #[serde(rename = "smokeless-powder")]
    SmokelessPowder = 269,
    #[serde(rename = "biomass-leaves")]
    BiomassLeaves = 270,
    #[serde(rename = "biomass-wood")]
    BiomassWood = 271,
    #[serde(rename = "reinforced-iron-plate")]
    ReinforcedIronPlate = 272,
    #[serde(rename = "concrete")]
    Concrete = 273,
    #[serde(rename = "screw")]
    Screw = 274,
    #[serde(rename = "cable")]
    Cable = 275,
    #[serde(rename = "wire")]
    Wire = 276,
    #[serde(rename = "copper-ingot")]
    CopperIngot = 277,
}

impl TryFrom<u16> for RecipeKind {
    type Error = ();
    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::NuclearWaste),
            1 => Ok(Self::PlutoniumWaste),
            2 => Ok(Self::IronPlate),
            3 => Ok(Self::IronRod),
            4 => Ok(Self::IronIngot),
            5 => Ok(Self::NitroRocketFuel),
            6 => Ok(Self::RocketFuel),
            7 => Ok(Self::PackagedRocketFuel),
            8 => Ok(Self::UnpackageRocketFuel),
            9 => Ok(Self::DarkIonFuel),
            10 => Ok(Self::DarkMatterResidue),
            11 => Ok(Self::ExcitedPhotonicMatter),
            12 => Ok(Self::DarkMatterCrystal),
            13 => Ok(Self::SuperpositionOscillator),
            14 => Ok(Self::NeuralQuantumProcessor),
            15 => Ok(Self::AiExpansionServer),
            16 => Ok(Self::IonizedFuel),
            17 => Ok(Self::PackagedIonizedFuel),
            18 => Ok(Self::UnpackageIonizedFuel),
            19 => Ok(Self::TurboDiamonds),
            20 => Ok(Self::SamFluctuator),
            21 => Ok(Self::FicsiteTrigon),
            22 => Ok(Self::FicsiteIngotIron),
            23 => Ok(Self::TimeCrystal),
            24 => Ok(Self::Diamonds),
            25 => Ok(Self::ReanimatedSam),
            26 => Ok(Self::BiochemicalSculptor),
            27 => Ok(Self::FicsiteIngotAluminum),
            28 => Ok(Self::FicsiteIngotCaterium),
            29 => Ok(Self::BauxiteCaterium),
            30 => Ok(Self::BauxiteCopper),
            31 => Ok(Self::CateriumOreCopper),
            32 => Ok(Self::CateriumOreQuartz),
            33 => Ok(Self::CoalIron),
            34 => Ok(Self::CoalLimestone),
            35 => Ok(Self::CopperOreQuartz),
            36 => Ok(Self::CopperOreSulfur),
            37 => Ok(Self::IronOreLimestone),
            38 => Ok(Self::LimestoneSulfur),
            39 => Ok(Self::NitrogenGasBauxite),
            40 => Ok(Self::NitrogenGasCaterium),
            41 => Ok(Self::RawQuartzBauxite),
            42 => Ok(Self::RawQuartzCoal),
            43 => Ok(Self::SulfurCoal),
            44 => Ok(Self::SulfurIron),
            45 => Ok(Self::UraniumOreBauxite),
            46 => Ok(Self::Turbofuel),
            47 => Ok(Self::PackagedTurbofuel),
            48 => Ok(Self::UnpackageTurbofuel),
            49 => Ok(Self::Charcoal),
            50 => Ok(Self::Biocoal),
            51 => Ok(Self::CompactedCoal),
            52 => Ok(Self::CircuitBoard),
            53 => Ok(Self::Fuel),
            54 => Ok(Self::PetroleumCoke),
            55 => Ok(Self::Plastic),
            56 => Ok(Self::Rubber),
            57 => Ok(Self::ResidualFuel),
            58 => Ok(Self::ResidualPlastic),
            59 => Ok(Self::ResidualRubber),
            60 => Ok(Self::PinkDiamonds),
            61 => Ok(Self::PetroleumDiamonds),
            62 => Ok(Self::OilBasedDiamonds),
            63 => Ok(Self::CloudyDiamonds),
            64 => Ok(Self::DarkMatterTrap),
            65 => Ok(Self::DarkMatterCrystallization),
            66 => Ok(Self::WetConcrete),
            67 => Ok(Self::TurboHeavyFuel),
            68 => Ok(Self::SteelRod),
            69 => Ok(Self::SteelBeam),
            70 => Ok(Self::SteelPipe),
            71 => Ok(Self::SteelIngot),
            72 => Ok(Self::VersatileFramework),
            73 => Ok(Self::SteelCanister),
            74 => Ok(Self::EmptyCanister),
            75 => Ok(Self::PackagedFuel),
            76 => Ok(Self::LiquidBiofuel),
            77 => Ok(Self::PackagedLiquidBiofuel),
            78 => Ok(Self::PackagedOil),
            79 => Ok(Self::PackagedHeavyOilResidue),
            80 => Ok(Self::PackagedWater),
            81 => Ok(Self::UnpackageLiquidBiofuel),
            82 => Ok(Self::UnpackageFuel),
            83 => Ok(Self::UnpackageOil),
            84 => Ok(Self::UnpackageHeavyOilResidue),
            85 => Ok(Self::UnpackageWater),
            86 => Ok(Self::SteamedCopperSheet),
            87 => Ok(Self::RubberConcrete),
            88 => Ok(Self::RecycledRubber),
            89 => Ok(Self::PureQuartzCrystal),
            90 => Ok(Self::QuartzCrystal),
            91 => Ok(Self::PureIronIngot),
            92 => Ok(Self::PureCopperIngot),
            93 => Ok(Self::PureCateriumIngot),
            94 => Ok(Self::PureAluminumIngot),
            95 => Ok(Self::AluminumCasing),
            96 => Ok(Self::AlcladAluminumSheet),
            97 => Ok(Self::AluminaSolution),
            98 => Ok(Self::AluminumScrap),
            99 => Ok(Self::PackagedAluminaSolution),
            100 => Ok(Self::AluminumIngot),
            101 => Ok(Self::Silica),
            102 => Ok(Self::CrystalOscillator),
            103 => Ok(Self::UnpackageAluminaSolution),
            104 => Ok(Self::PolymerResin),
            105 => Ok(Self::PlasticSmartPlating),
            106 => Ok(Self::AutomatedSpeedWiring),
            107 => Ok(Self::EncasedIndustrialBeam),
            108 => Ok(Self::Motor),
            109 => Ok(Self::Stator),
            110 => Ok(Self::AutomatedWiring),
            111 => Ok(Self::AiLimiter),
            112 => Ok(Self::HeavyOilResidue),
            113 => Ok(Self::HeavyFlexibleFrame),
            114 => Ok(Self::Computer),
            115 => Ok(Self::HeavyModularFrame),
            116 => Ok(Self::ModularEngine),
            117 => Ok(Self::AdaptiveControlUnit),
            118 => Ok(Self::FusedWire),
            119 => Ok(Self::FlexibleFramework),
            120 => Ok(Self::ElectrodeCircuitBoard),
            121 => Ok(Self::ElectrodeAluminumScrap),
            122 => Ok(Self::DilutedPackagedFuel),
            123 => Ok(Self::CopperRotor),
            124 => Ok(Self::ModularFrame),
            125 => Ok(Self::Rotor),
            126 => Ok(Self::CopperSheet),
            127 => Ok(Self::SmartPlating),
            128 => Ok(Self::CopperAlloyIngot),
            129 => Ok(Self::CokeSteelIngot),
            130 => Ok(Self::CoatedIronPlate),
            131 => Ok(Self::CoatedIronCanister),
            132 => Ok(Self::CoatedCable),
            133 => Ok(Self::BoltedFrame),
            134 => Ok(Self::AdheredIronPlate),
            135 => Ok(Self::TurboPressureMotor),
            136 => Ok(Self::EncasedPlutoniumCell),
            137 => Ok(Self::PressureConversionCube),
            138 => Ok(Self::NitricAcid),
            139 => Ok(Self::NonFissileUranium),
            140 => Ok(Self::CopperPowder),
            141 => Ok(Self::PlutoniumPellet),
            142 => Ok(Self::PlutoniumFuelRod),
            143 => Ok(Self::PackagedNitricAcid),
            144 => Ok(Self::NuclearPasta),
            145 => Ok(Self::UnpackageNitricAcid),
            146 => Ok(Self::TurboBlendFuel),
            147 => Ok(Self::EncasedUraniumCell),
            148 => Ok(Self::CoolingSystem),
            149 => Ok(Self::Battery),
            150 => Ok(Self::Supercomputer),
            151 => Ok(Self::RadioControlUnit),
            152 => Ok(Self::SulfuricAcid),
            153 => Ok(Self::PackagedSulfuricAcid),
            154 => Ok(Self::AssemblyDirectorSystem),
            155 => Ok(Self::HighSpeedConnector),
            156 => Ok(Self::UnpackageSulfuricAcid),
            157 => Ok(Self::SuperStateComputer),
            158 => Ok(Self::ElectromagneticControlRod),
            159 => Ok(Self::UraniumFuelRod),
            160 => Ok(Self::MagneticFieldGenerator),
            161 => Ok(Self::SloppyAlumina),
            162 => Ok(Self::RadioControlSystem),
            163 => Ok(Self::PlutoniumFuelUnit),
            164 => Ok(Self::OcSupercomputer),
            165 => Ok(Self::HeatSink),
            166 => Ok(Self::FusedModularFrame),
            167 => Ok(Self::EmptyFluidTank),
            168 => Ok(Self::PackagedNitrogenGas),
            169 => Ok(Self::UnpackageNitrogenGas),
            170 => Ok(Self::InstantScrap),
            171 => Ok(Self::InstantPlutoniumCell),
            172 => Ok(Self::HeatFusedFrame),
            173 => Ok(Self::FertileUranium),
            174 => Ok(Self::ElectricMotor),
            175 => Ok(Self::DilutedFuel),
            176 => Ok(Self::CoolingDevice),
            177 => Ok(Self::ClassicBattery),
            178 => Ok(Self::AutomatedMiner),
            179 => Ok(Self::AlcladCasing),
            180 => Ok(Self::MoldedSteelPipe),
            181 => Ok(Self::IronPipe),
            182 => Ok(Self::SteelCastPlate),
            183 => Ok(Self::MoldedBeam),
            184 => Ok(Self::AluminumBeam),
            185 => Ok(Self::AluminumRod),
            186 => Ok(Self::PlasticAiLimiter),
            187 => Ok(Self::DistilledSilica),
            188 => Ok(Self::QuartzPurification),
            189 => Ok(Self::FusedQuartzCrystal),
            190 => Ok(Self::LeachedIronIngot),
            191 => Ok(Self::BasicIronIngot),
            192 => Ok(Self::TemperedCopperIngot),
            193 => Ok(Self::LeachedCopperIngot),
            194 => Ok(Self::TemperedCateriumIngot),
            195 => Ok(Self::LeachedCateriumIngot),
            196 => Ok(Self::CateriumWire),
            197 => Ok(Self::IronWire),
            198 => Ok(Self::InfusedUraniumCell),
            199 => Ok(Self::CateriumIngot),
            200 => Ok(Self::TurboElectricMotor),
            201 => Ok(Self::TurboMotor),
            202 => Ok(Self::ThermalPropulsionRocket),
            203 => Ok(Self::QuickwireStator),
            204 => Ok(Self::CheapSilica),
            205 => Ok(Self::SteelScrew),
            206 => Ok(Self::CastScrew),
            207 => Ok(Self::SteelRotor),
            208 => Ok(Self::EncasedIndustrialPipe),
            209 => Ok(Self::StitchedIronPlate),
            210 => Ok(Self::BoltedIronPlate),
            211 => Ok(Self::RadioConnectionUnit),
            212 => Ok(Self::FusedQuickwire),
            213 => Ok(Self::RecycledPlastic),
            214 => Ok(Self::UraniumFuelUnit),
            215 => Ok(Self::RigorMotor),
            216 => Ok(Self::SteeledFrame),
            217 => Ok(Self::CompactedSteelIngot),
            218 => Ok(Self::SolidSteelIngot),
            219 => Ok(Self::IronAlloyIngot),
            220 => Ok(Self::SiliconHighSpeedConnector),
            221 => Ok(Self::HeavyEncasedFrame),
            222 => Ok(Self::HeatExchanger),
            223 => Ok(Self::FineBlackPowder),
            224 => Ok(Self::ElectromagneticConnectionRod),
            225 => Ok(Self::InsulatedCrystalOscillator),
            226 => Ok(Self::FineConcrete),
            227 => Ok(Self::CrystalComputer),
            228 => Ok(Self::CateriumComputer),
            229 => Ok(Self::CateriumCircuitBoard),
            230 => Ok(Self::SiliconCircuitBoard),
            231 => Ok(Self::QuickwireCable),
            232 => Ok(Self::InsulatedCable),
            233 => Ok(Self::Ficsonium),
            234 => Ok(Self::FicsoniumFuelRod),
            235 => Ok(Self::SingularityCell),
            236 => Ok(Self::BallisticWarpDrive),
            237 => Ok(Self::IodineInfusedFilter),
            238 => Ok(Self::Quickwire),
            239 => Ok(Self::SolidBiofuel),
            240 => Ok(Self::HogProtein),
            241 => Ok(Self::SpitterProtein),
            242 => Ok(Self::BiomassMycelia),
            243 => Ok(Self::PowerShard1),
            244 => Ok(Self::BlackPowder),
            245 => Ok(Self::AlienPowerMatrix),
            246 => Ok(Self::StingerProtein),
            247 => Ok(Self::HatcherProtein),
            248 => Ok(Self::AlienDnaCapsule),
            249 => Ok(Self::BiomassAlienProtein),
            250 => Ok(Self::IronRebar),
            251 => Ok(Self::HomingRifleAmmo),
            252 => Ok(Self::StunRebar),
            253 => Ok(Self::GasFilter),
            254 => Ok(Self::GasNobelisk),
            255 => Ok(Self::PolyesterFabric),
            256 => Ok(Self::Fabric),
            257 => Ok(Self::SyntheticPowerShard),
            258 => Ok(Self::PowerShard5),
            259 => Ok(Self::PowerShard2),
            260 => Ok(Self::PulseNobelisk),
            261 => Ok(Self::ShatterRebar),
            262 => Ok(Self::TurboRifleAmmoPackaged),
            263 => Ok(Self::TurboRifleAmmo),
            264 => Ok(Self::NukeNobelisk),
            265 => Ok(Self::RifleAmmo),
            266 => Ok(Self::ExplosiveRebar),
            267 => Ok(Self::ClusterNobelisk),
            268 => Ok(Self::Nobelisk),
            269 => Ok(Self::SmokelessPowder),
            270 => Ok(Self::BiomassLeaves),
            271 => Ok(Self::BiomassWood),
            272 => Ok(Self::ReinforcedIronPlate),
            273 => Ok(Self::Concrete),
            274 => Ok(Self::Screw),
            275 => Ok(Self::Cable),
            276 => Ok(Self::Wire),
            277 => Ok(Self::CopperIngot),
            _ => Err(()),
        }
    }
}

impl RecipeKind {
    pub fn info(self) -> &'static RecipeInfo {
        &RECIPES[self as u16 as usize]
    }
}

pub struct RecipeInfo {
    pub name: &'static str,
    pub inputs: &'static [ItemKind],
    pub outputs: &'static [ItemKind],
}

const RECIPES: [RecipeInfo; 278] = [
    RecipeInfo {
        name: "Uranium Fuel Rod (burning)",
        inputs: &[ItemKind::UraniumFuelRod, ItemKind::Water],
        outputs: &[ItemKind::UraniumWaste],
    },
    RecipeInfo {
        name: "Plutonium Fuel Rod (burning)",
        inputs: &[ItemKind::PlutoniumFuelRod, ItemKind::Water],
        outputs: &[ItemKind::PlutoniumWaste],
    },
    RecipeInfo {
        name: "Iron Plate",
        inputs: &[ItemKind::IronIngot],
        outputs: &[ItemKind::IronPlate],
    },
    RecipeInfo {
        name: "Iron Rod",
        inputs: &[ItemKind::IronIngot],
        outputs: &[ItemKind::IronRod],
    },
    RecipeInfo {
        name: "Iron Ingot",
        inputs: &[ItemKind::IronOre],
        outputs: &[ItemKind::IronIngot],
    },
    RecipeInfo {
        name: "Nitro Rocket Fuel",
        inputs: &[ItemKind::Fuel, ItemKind::NitrogenGas, ItemKind::Sulfur, ItemKind::Coal],
        outputs: &[ItemKind::RocketFuel, ItemKind::CompactedCoal],
    },
    RecipeInfo {
        name: "Rocket Fuel",
        inputs: &[ItemKind::Turbofuel, ItemKind::NitricAcid],
        outputs: &[ItemKind::RocketFuel, ItemKind::CompactedCoal],
    },
    RecipeInfo {
        name: "Packaged Rocket Fuel",
        inputs: &[ItemKind::RocketFuel, ItemKind::EmptyFluidTank],
        outputs: &[ItemKind::PackagedRocketFuel],
    },
    RecipeInfo {
        name: "Unpackage Rocket Fuel",
        inputs: &[ItemKind::PackagedRocketFuel],
        outputs: &[ItemKind::RocketFuel, ItemKind::EmptyFluidTank],
    },
    RecipeInfo {
        name: "Dark-Ion Fuel",
        inputs: &[ItemKind::PackagedRocketFuel, ItemKind::DarkMatterCrystal],
        outputs: &[ItemKind::IonizedFuel, ItemKind::CompactedCoal],
    },
    RecipeInfo {
        name: "Dark Matter Residue",
        inputs: &[ItemKind::ReanimatedSam],
        outputs: &[ItemKind::DarkMatterResidue],
    },
    RecipeInfo {
        name: "Excited Photonic Matter",
        inputs: &[],
        outputs: &[ItemKind::ExcitedPhotonicMatter],
    },
    RecipeInfo {
        name: "Dark Matter Crystal",
        inputs: &[ItemKind::Diamonds, ItemKind::DarkMatterResidue],
        outputs: &[ItemKind::DarkMatterCrystal],
    },
    RecipeInfo {
        name: "Superposition Oscillator",
        inputs: &[ItemKind::DarkMatterCrystal, ItemKind::CrystalOscillator, ItemKind::AlcladAluminumSheet, ItemKind::ExcitedPhotonicMatter],
        outputs: &[ItemKind::SuperpositionOscillator, ItemKind::DarkMatterResidue],
    },
    RecipeInfo {
        name: "Neural-Quantum Processor",
        inputs: &[ItemKind::TimeCrystal, ItemKind::Supercomputer, ItemKind::FicsiteTrigon, ItemKind::ExcitedPhotonicMatter],
        outputs: &[ItemKind::NeuralQuantumProcessor, ItemKind::DarkMatterResidue],
    },
    RecipeInfo {
        name: "AI Expansion Server",
        inputs: &[ItemKind::MagneticFieldGenerator, ItemKind::NeuralQuantumProcessor, ItemKind::SuperpositionOscillator, ItemKind::ExcitedPhotonicMatter],
        outputs: &[ItemKind::AiExpansionServer, ItemKind::DarkMatterResidue],
    },
    RecipeInfo {
        name: "Ionized Fuel",
        inputs: &[ItemKind::RocketFuel, ItemKind::PowerShard],
        outputs: &[ItemKind::IonizedFuel, ItemKind::CompactedCoal],
    },
    RecipeInfo {
        name: "Packaged Ionized Fuel",
        inputs: &[ItemKind::IonizedFuel, ItemKind::EmptyFluidTank],
        outputs: &[ItemKind::PackagedIonizedFuel],
    },
    RecipeInfo {
        name: "Unpackage Ionized Fuel",
        inputs: &[ItemKind::PackagedIonizedFuel],
        outputs: &[ItemKind::IonizedFuel, ItemKind::EmptyFluidTank],
    },
    RecipeInfo {
        name: "Turbo Diamonds",
        inputs: &[ItemKind::Coal, ItemKind::PackagedTurbofuel],
        outputs: &[ItemKind::Diamonds],
    },
    RecipeInfo {
        name: "SAM Fluctuator",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Wire, ItemKind::SteelPipe],
        outputs: &[ItemKind::SamFluctuator],
    },
    RecipeInfo {
        name: "Ficsite Trigon",
        inputs: &[ItemKind::FicsiteIngot],
        outputs: &[ItemKind::FicsiteTrigon],
    },
    RecipeInfo {
        name: "Ficsite Ingot (Iron)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::IronIngot],
        outputs: &[ItemKind::FicsiteIngot],
    },
    RecipeInfo {
        name: "Time Crystal",
        inputs: &[ItemKind::Diamonds],
        outputs: &[ItemKind::TimeCrystal],
    },
    RecipeInfo {
        name: "Diamonds",
        inputs: &[ItemKind::Coal],
        outputs: &[ItemKind::Diamonds],
    },
    RecipeInfo {
        name: "Reanimated SAM",
        inputs: &[ItemKind::Sam],
        outputs: &[ItemKind::ReanimatedSam],
    },
    RecipeInfo {
        name: "Biochemical Sculptor",
        inputs: &[ItemKind::AssemblyDirectorSystem, ItemKind::FicsiteTrigon, ItemKind::Water],
        outputs: &[ItemKind::BiochemicalSculptor],
    },
    RecipeInfo {
        name: "Ficsite Ingot (Aluminum)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::AluminumIngot],
        outputs: &[ItemKind::FicsiteIngot],
    },
    RecipeInfo {
        name: "Ficsite Ingot (Caterium)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::CateriumIngot],
        outputs: &[ItemKind::FicsiteIngot],
    },
    RecipeInfo {
        name: "Bauxite (Caterium)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::CateriumOre],
        outputs: &[ItemKind::Bauxite],
    },
    RecipeInfo {
        name: "Bauxite (Copper)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::CopperOre],
        outputs: &[ItemKind::Bauxite],
    },
    RecipeInfo {
        name: "Caterium Ore (Copper)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::CopperOre],
        outputs: &[ItemKind::CateriumOre],
    },
    RecipeInfo {
        name: "Caterium Ore (Quartz)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::RawQuartz],
        outputs: &[ItemKind::CateriumOre],
    },
    RecipeInfo {
        name: "Coal (Iron)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::IronOre],
        outputs: &[ItemKind::Coal],
    },
    RecipeInfo {
        name: "Coal (Limestone)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Limestone],
        outputs: &[ItemKind::Coal],
    },
    RecipeInfo {
        name: "Copper Ore (Quartz)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::RawQuartz],
        outputs: &[ItemKind::CopperOre],
    },
    RecipeInfo {
        name: "Copper Ore (Sulfur)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Sulfur],
        outputs: &[ItemKind::CopperOre],
    },
    RecipeInfo {
        name: "Iron Ore (Limestone)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Limestone],
        outputs: &[ItemKind::IronOre],
    },
    RecipeInfo {
        name: "Limestone (Sulfur)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Sulfur],
        outputs: &[ItemKind::Limestone],
    },
    RecipeInfo {
        name: "Nitrogen Gas (Bauxite)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Bauxite],
        outputs: &[ItemKind::NitrogenGas],
    },
    RecipeInfo {
        name: "Nitrogen Gas (Caterium)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::CateriumOre],
        outputs: &[ItemKind::NitrogenGas],
    },
    RecipeInfo {
        name: "Raw Quartz (Bauxite)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Bauxite],
        outputs: &[ItemKind::RawQuartz],
    },
    RecipeInfo {
        name: "Raw Quartz (Coal)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Coal],
        outputs: &[ItemKind::RawQuartz],
    },
    RecipeInfo {
        name: "Sulfur (Coal)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Coal],
        outputs: &[ItemKind::Sulfur],
    },
    RecipeInfo {
        name: "Sulfur (Iron)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::IronOre],
        outputs: &[ItemKind::Sulfur],
    },
    RecipeInfo {
        name: "Uranium Ore (Bauxite)",
        inputs: &[ItemKind::ReanimatedSam, ItemKind::Bauxite],
        outputs: &[ItemKind::Uranium],
    },
    RecipeInfo {
        name: "Turbofuel",
        inputs: &[ItemKind::Fuel, ItemKind::CompactedCoal],
        outputs: &[ItemKind::Turbofuel],
    },
    RecipeInfo {
        name: "Packaged Turbofuel",
        inputs: &[ItemKind::Turbofuel, ItemKind::EmptyCanister],
        outputs: &[ItemKind::PackagedTurbofuel],
    },
    RecipeInfo {
        name: "Unpackage Turbofuel",
        inputs: &[ItemKind::PackagedTurbofuel],
        outputs: &[ItemKind::Turbofuel, ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Charcoal",
        inputs: &[ItemKind::Wood],
        outputs: &[ItemKind::Coal],
    },
    RecipeInfo {
        name: "Biocoal",
        inputs: &[ItemKind::Biomass],
        outputs: &[ItemKind::Coal],
    },
    RecipeInfo {
        name: "Compacted Coal",
        inputs: &[ItemKind::Coal, ItemKind::Sulfur],
        outputs: &[ItemKind::CompactedCoal],
    },
    RecipeInfo {
        name: "Circuit Board",
        inputs: &[ItemKind::CopperSheet, ItemKind::Plastic],
        outputs: &[ItemKind::CircuitBoard],
    },
    RecipeInfo {
        name: "Fuel",
        inputs: &[ItemKind::CrudeOil],
        outputs: &[ItemKind::Fuel, ItemKind::PolymerResin],
    },
    RecipeInfo {
        name: "Petroleum Coke",
        inputs: &[ItemKind::HeavyOilResidue],
        outputs: &[ItemKind::PetroleumCoke],
    },
    RecipeInfo {
        name: "Plastic",
        inputs: &[ItemKind::CrudeOil],
        outputs: &[ItemKind::Plastic, ItemKind::HeavyOilResidue],
    },
    RecipeInfo {
        name: "Rubber",
        inputs: &[ItemKind::CrudeOil],
        outputs: &[ItemKind::Rubber, ItemKind::HeavyOilResidue],
    },
    RecipeInfo {
        name: "Residual Fuel",
        inputs: &[ItemKind::HeavyOilResidue],
        outputs: &[ItemKind::Fuel],
    },
    RecipeInfo {
        name: "Residual Plastic",
        inputs: &[ItemKind::PolymerResin, ItemKind::Water],
        outputs: &[ItemKind::Plastic],
    },
    RecipeInfo {
        name: "Residual Rubber",
        inputs: &[ItemKind::PolymerResin, ItemKind::Water],
        outputs: &[ItemKind::Rubber],
    },
    RecipeInfo {
        name: "Pink Diamonds",
        inputs: &[ItemKind::Coal, ItemKind::QuartzCrystal],
        outputs: &[ItemKind::Diamonds],
    },
    RecipeInfo {
        name: "Petroleum Diamonds",
        inputs: &[ItemKind::PetroleumCoke],
        outputs: &[ItemKind::Diamonds],
    },
    RecipeInfo {
        name: "Oil-Based Diamonds",
        inputs: &[ItemKind::CrudeOil],
        outputs: &[ItemKind::Diamonds],
    },
    RecipeInfo {
        name: "Cloudy Diamonds",
        inputs: &[ItemKind::Coal, ItemKind::Limestone],
        outputs: &[ItemKind::Diamonds],
    },
    RecipeInfo {
        name: "Dark Matter Trap",
        inputs: &[ItemKind::TimeCrystal, ItemKind::DarkMatterResidue],
        outputs: &[ItemKind::DarkMatterCrystal],
    },
    RecipeInfo {
        name: "Dark Matter Crystallization",
        inputs: &[ItemKind::DarkMatterResidue],
        outputs: &[ItemKind::DarkMatterCrystal],
    },
    RecipeInfo {
        name: "Wet Concrete",
        inputs: &[ItemKind::Limestone, ItemKind::Water],
        outputs: &[ItemKind::Concrete],
    },
    RecipeInfo {
        name: "Turbo Heavy Fuel",
        inputs: &[ItemKind::HeavyOilResidue, ItemKind::CompactedCoal],
        outputs: &[ItemKind::Turbofuel],
    },
    RecipeInfo {
        name: "Steel Rod",
        inputs: &[ItemKind::SteelIngot],
        outputs: &[ItemKind::IronRod],
    },
    RecipeInfo {
        name: "Steel Beam",
        inputs: &[ItemKind::SteelIngot],
        outputs: &[ItemKind::SteelBeam],
    },
    RecipeInfo {
        name: "Steel Pipe",
        inputs: &[ItemKind::SteelIngot],
        outputs: &[ItemKind::SteelPipe],
    },
    RecipeInfo {
        name: "Steel Ingot",
        inputs: &[ItemKind::IronOre, ItemKind::Coal],
        outputs: &[ItemKind::SteelIngot],
    },
    RecipeInfo {
        name: "Versatile Framework",
        inputs: &[ItemKind::ModularFrame, ItemKind::SteelBeam],
        outputs: &[ItemKind::VersatileFramework],
    },
    RecipeInfo {
        name: "Steel Canister",
        inputs: &[ItemKind::SteelIngot],
        outputs: &[ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Empty Canister",
        inputs: &[ItemKind::Plastic],
        outputs: &[ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Packaged Fuel",
        inputs: &[ItemKind::Fuel, ItemKind::EmptyCanister],
        outputs: &[ItemKind::PackagedFuel],
    },
    RecipeInfo {
        name: "Liquid Biofuel",
        inputs: &[ItemKind::SolidBiofuel, ItemKind::Water],
        outputs: &[ItemKind::LiquidBiofuel],
    },
    RecipeInfo {
        name: "Packaged Liquid Biofuel",
        inputs: &[ItemKind::LiquidBiofuel, ItemKind::EmptyCanister],
        outputs: &[ItemKind::PackagedLiquidBiofuel],
    },
    RecipeInfo {
        name: "Packaged Oil",
        inputs: &[ItemKind::CrudeOil, ItemKind::EmptyCanister],
        outputs: &[ItemKind::PackagedOil],
    },
    RecipeInfo {
        name: "Packaged Heavy Oil Residue",
        inputs: &[ItemKind::HeavyOilResidue, ItemKind::EmptyCanister],
        outputs: &[ItemKind::PackagedHeavyOilResidue],
    },
    RecipeInfo {
        name: "Packaged Water",
        inputs: &[ItemKind::Water, ItemKind::EmptyCanister],
        outputs: &[ItemKind::PackagedWater],
    },
    RecipeInfo {
        name: "Unpackage Liquid Biofuel",
        inputs: &[ItemKind::PackagedLiquidBiofuel],
        outputs: &[ItemKind::LiquidBiofuel, ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Unpackage Fuel",
        inputs: &[ItemKind::PackagedFuel],
        outputs: &[ItemKind::Fuel, ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Unpackage Oil",
        inputs: &[ItemKind::PackagedOil],
        outputs: &[ItemKind::CrudeOil, ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Unpackage Heavy Oil Residue",
        inputs: &[ItemKind::PackagedHeavyOilResidue],
        outputs: &[ItemKind::HeavyOilResidue, ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Unpackage Water",
        inputs: &[ItemKind::PackagedWater],
        outputs: &[ItemKind::Water, ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Steamed Copper Sheet",
        inputs: &[ItemKind::CopperIngot, ItemKind::Water],
        outputs: &[ItemKind::CopperSheet],
    },
    RecipeInfo {
        name: "Rubber Concrete",
        inputs: &[ItemKind::Limestone, ItemKind::Rubber],
        outputs: &[ItemKind::Concrete],
    },
    RecipeInfo {
        name: "Recycled Rubber",
        inputs: &[ItemKind::Plastic, ItemKind::Fuel],
        outputs: &[ItemKind::Rubber],
    },
    RecipeInfo {
        name: "Pure Quartz Crystal",
        inputs: &[ItemKind::RawQuartz, ItemKind::Water],
        outputs: &[ItemKind::QuartzCrystal],
    },
    RecipeInfo {
        name: "Quartz Crystal",
        inputs: &[ItemKind::RawQuartz],
        outputs: &[ItemKind::QuartzCrystal],
    },
    RecipeInfo {
        name: "Pure Iron Ingot",
        inputs: &[ItemKind::IronOre, ItemKind::Water],
        outputs: &[ItemKind::IronIngot],
    },
    RecipeInfo {
        name: "Pure Copper Ingot",
        inputs: &[ItemKind::CopperOre, ItemKind::Water],
        outputs: &[ItemKind::CopperIngot],
    },
    RecipeInfo {
        name: "Pure Caterium Ingot",
        inputs: &[ItemKind::CateriumOre, ItemKind::Water],
        outputs: &[ItemKind::CateriumIngot],
    },
    RecipeInfo {
        name: "Pure Aluminum Ingot",
        inputs: &[ItemKind::AluminumScrap],
        outputs: &[ItemKind::AluminumIngot],
    },
    RecipeInfo {
        name: "Aluminum Casing",
        inputs: &[ItemKind::AluminumIngot],
        outputs: &[ItemKind::AluminumCasing],
    },
    RecipeInfo {
        name: "Alclad Aluminum Sheet",
        inputs: &[ItemKind::AluminumIngot, ItemKind::CopperIngot],
        outputs: &[ItemKind::AlcladAluminumSheet],
    },
    RecipeInfo {
        name: "Alumina Solution",
        inputs: &[ItemKind::Bauxite, ItemKind::Water],
        outputs: &[ItemKind::AluminaSolution, ItemKind::Silica],
    },
    RecipeInfo {
        name: "Aluminum Scrap",
        inputs: &[ItemKind::AluminaSolution, ItemKind::Coal],
        outputs: &[ItemKind::AluminumScrap, ItemKind::Water],
    },
    RecipeInfo {
        name: "Packaged Alumina Solution",
        inputs: &[ItemKind::AluminaSolution, ItemKind::EmptyCanister],
        outputs: &[ItemKind::PackagedAluminaSolution],
    },
    RecipeInfo {
        name: "Aluminum Ingot",
        inputs: &[ItemKind::AluminumScrap, ItemKind::Silica],
        outputs: &[ItemKind::AluminumIngot],
    },
    RecipeInfo {
        name: "Silica",
        inputs: &[ItemKind::RawQuartz],
        outputs: &[ItemKind::Silica],
    },
    RecipeInfo {
        name: "Crystal Oscillator",
        inputs: &[ItemKind::QuartzCrystal, ItemKind::Cable, ItemKind::ReinforcedIronPlate],
        outputs: &[ItemKind::CrystalOscillator],
    },
    RecipeInfo {
        name: "Unpackage Alumina Solution",
        inputs: &[ItemKind::PackagedAluminaSolution],
        outputs: &[ItemKind::AluminaSolution, ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Polymer Resin",
        inputs: &[ItemKind::CrudeOil],
        outputs: &[ItemKind::PolymerResin, ItemKind::HeavyOilResidue],
    },
    RecipeInfo {
        name: "Plastic Smart Plating",
        inputs: &[ItemKind::ReinforcedIronPlate, ItemKind::Rotor, ItemKind::Plastic],
        outputs: &[ItemKind::SmartPlating],
    },
    RecipeInfo {
        name: "Automated Speed Wiring",
        inputs: &[ItemKind::Stator, ItemKind::Wire, ItemKind::HighSpeedConnector],
        outputs: &[ItemKind::AutomatedWiring],
    },
    RecipeInfo {
        name: "Encased Industrial Beam",
        inputs: &[ItemKind::SteelBeam, ItemKind::Concrete],
        outputs: &[ItemKind::EncasedIndustrialBeam],
    },
    RecipeInfo {
        name: "Motor",
        inputs: &[ItemKind::Rotor, ItemKind::Stator],
        outputs: &[ItemKind::Motor],
    },
    RecipeInfo {
        name: "Stator",
        inputs: &[ItemKind::SteelPipe, ItemKind::Wire],
        outputs: &[ItemKind::Stator],
    },
    RecipeInfo {
        name: "Automated Wiring",
        inputs: &[ItemKind::Stator, ItemKind::Cable],
        outputs: &[ItemKind::AutomatedWiring],
    },
    RecipeInfo {
        name: "AI Limiter",
        inputs: &[ItemKind::CopperSheet, ItemKind::Quickwire],
        outputs: &[ItemKind::AiLimiter],
    },
    RecipeInfo {
        name: "Heavy Oil Residue",
        inputs: &[ItemKind::CrudeOil],
        outputs: &[ItemKind::HeavyOilResidue, ItemKind::PolymerResin],
    },
    RecipeInfo {
        name: "Heavy Flexible Frame",
        inputs: &[ItemKind::ModularFrame, ItemKind::EncasedIndustrialBeam, ItemKind::Rubber, ItemKind::Screw],
        outputs: &[ItemKind::HeavyModularFrame],
    },
    RecipeInfo {
        name: "Computer",
        inputs: &[ItemKind::CircuitBoard, ItemKind::Cable, ItemKind::Plastic],
        outputs: &[ItemKind::Computer],
    },
    RecipeInfo {
        name: "Heavy Modular Frame",
        inputs: &[ItemKind::ModularFrame, ItemKind::SteelPipe, ItemKind::EncasedIndustrialBeam, ItemKind::Screw],
        outputs: &[ItemKind::HeavyModularFrame],
    },
    RecipeInfo {
        name: "Modular Engine",
        inputs: &[ItemKind::Motor, ItemKind::Rubber, ItemKind::SmartPlating],
        outputs: &[ItemKind::ModularEngine],
    },
    RecipeInfo {
        name: "Adaptive Control Unit",
        inputs: &[ItemKind::AutomatedWiring, ItemKind::CircuitBoard, ItemKind::HeavyModularFrame, ItemKind::Computer],
        outputs: &[ItemKind::AdaptiveControlUnit],
    },
    RecipeInfo {
        name: "Fused Wire",
        inputs: &[ItemKind::CopperIngot, ItemKind::CateriumIngot],
        outputs: &[ItemKind::Wire],
    },
    RecipeInfo {
        name: "Flexible Framework",
        inputs: &[ItemKind::ModularFrame, ItemKind::SteelBeam, ItemKind::Rubber],
        outputs: &[ItemKind::VersatileFramework],
    },
    RecipeInfo {
        name: "Electrode Circuit Board",
        inputs: &[ItemKind::Rubber, ItemKind::PetroleumCoke],
        outputs: &[ItemKind::CircuitBoard],
    },
    RecipeInfo {
        name: "Electrode Aluminum Scrap",
        inputs: &[ItemKind::AluminaSolution, ItemKind::PetroleumCoke],
        outputs: &[ItemKind::AluminumScrap, ItemKind::Water],
    },
    RecipeInfo {
        name: "Diluted Packaged Fuel",
        inputs: &[ItemKind::HeavyOilResidue, ItemKind::PackagedWater],
        outputs: &[ItemKind::PackagedFuel],
    },
    RecipeInfo {
        name: "Copper Rotor",
        inputs: &[ItemKind::CopperSheet, ItemKind::Screw],
        outputs: &[ItemKind::Rotor],
    },
    RecipeInfo {
        name: "Modular Frame",
        inputs: &[ItemKind::ReinforcedIronPlate, ItemKind::IronRod],
        outputs: &[ItemKind::ModularFrame],
    },
    RecipeInfo {
        name: "Rotor",
        inputs: &[ItemKind::IronRod, ItemKind::Screw],
        outputs: &[ItemKind::Rotor],
    },
    RecipeInfo {
        name: "Copper Sheet",
        inputs: &[ItemKind::CopperIngot],
        outputs: &[ItemKind::CopperSheet],
    },
    RecipeInfo {
        name: "Smart Plating",
        inputs: &[ItemKind::ReinforcedIronPlate, ItemKind::Rotor],
        outputs: &[ItemKind::SmartPlating],
    },
    RecipeInfo {
        name: "Copper Alloy Ingot",
        inputs: &[ItemKind::CopperOre, ItemKind::IronOre],
        outputs: &[ItemKind::CopperIngot],
    },
    RecipeInfo {
        name: "Coke Steel Ingot",
        inputs: &[ItemKind::IronOre, ItemKind::PetroleumCoke],
        outputs: &[ItemKind::SteelIngot],
    },
    RecipeInfo {
        name: "Coated Iron Plate",
        inputs: &[ItemKind::IronIngot, ItemKind::Plastic],
        outputs: &[ItemKind::IronPlate],
    },
    RecipeInfo {
        name: "Coated Iron Canister",
        inputs: &[ItemKind::IronPlate, ItemKind::CopperSheet],
        outputs: &[ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Coated Cable",
        inputs: &[ItemKind::Wire, ItemKind::HeavyOilResidue],
        outputs: &[ItemKind::Cable],
    },
    RecipeInfo {
        name: "Bolted Frame",
        inputs: &[ItemKind::ReinforcedIronPlate, ItemKind::Screw],
        outputs: &[ItemKind::ModularFrame],
    },
    RecipeInfo {
        name: "Adhered Iron Plate",
        inputs: &[ItemKind::IronPlate, ItemKind::Rubber],
        outputs: &[ItemKind::ReinforcedIronPlate],
    },
    RecipeInfo {
        name: "Turbo Pressure Motor",
        inputs: &[ItemKind::Motor, ItemKind::PressureConversionCube, ItemKind::PackagedNitrogenGas, ItemKind::Stator],
        outputs: &[ItemKind::TurboMotor],
    },
    RecipeInfo {
        name: "Encased Plutonium Cell",
        inputs: &[ItemKind::PlutoniumPellet, ItemKind::Concrete],
        outputs: &[ItemKind::EncasedPlutoniumCell],
    },
    RecipeInfo {
        name: "Pressure Conversion Cube",
        inputs: &[ItemKind::FusedModularFrame, ItemKind::RadioControlUnit],
        outputs: &[ItemKind::PressureConversionCube],
    },
    RecipeInfo {
        name: "Nitric Acid",
        inputs: &[ItemKind::NitrogenGas, ItemKind::Water, ItemKind::IronPlate],
        outputs: &[ItemKind::NitricAcid],
    },
    RecipeInfo {
        name: "Non-Fissile Uranium",
        inputs: &[ItemKind::UraniumWaste, ItemKind::Silica, ItemKind::NitricAcid, ItemKind::SulfuricAcid],
        outputs: &[ItemKind::NonFissileUranium, ItemKind::Water],
    },
    RecipeInfo {
        name: "Copper Powder",
        inputs: &[ItemKind::CopperIngot],
        outputs: &[ItemKind::CopperPowder],
    },
    RecipeInfo {
        name: "Plutonium Pellet",
        inputs: &[ItemKind::NonFissileUranium, ItemKind::UraniumWaste],
        outputs: &[ItemKind::PlutoniumPellet],
    },
    RecipeInfo {
        name: "Plutonium Fuel Rod",
        inputs: &[ItemKind::EncasedPlutoniumCell, ItemKind::SteelBeam, ItemKind::ElectromagneticControlRod, ItemKind::HeatSink],
        outputs: &[ItemKind::PlutoniumFuelRod],
    },
    RecipeInfo {
        name: "Packaged Nitric Acid",
        inputs: &[ItemKind::NitricAcid, ItemKind::EmptyFluidTank],
        outputs: &[ItemKind::PackagedNitricAcid],
    },
    RecipeInfo {
        name: "Nuclear Pasta",
        inputs: &[ItemKind::CopperPowder, ItemKind::PressureConversionCube],
        outputs: &[ItemKind::NuclearPasta],
    },
    RecipeInfo {
        name: "Unpackage Nitric Acid",
        inputs: &[ItemKind::PackagedNitricAcid],
        outputs: &[ItemKind::NitricAcid, ItemKind::EmptyFluidTank],
    },
    RecipeInfo {
        name: "Turbo Blend Fuel",
        inputs: &[ItemKind::Fuel, ItemKind::HeavyOilResidue, ItemKind::Sulfur, ItemKind::PetroleumCoke],
        outputs: &[ItemKind::Turbofuel],
    },
    RecipeInfo {
        name: "Encased Uranium Cell",
        inputs: &[ItemKind::Uranium, ItemKind::Concrete, ItemKind::SulfuricAcid],
        outputs: &[ItemKind::EncasedUraniumCell, ItemKind::SulfuricAcid],
    },
    RecipeInfo {
        name: "Cooling System",
        inputs: &[ItemKind::HeatSink, ItemKind::Rubber, ItemKind::Water, ItemKind::NitrogenGas],
        outputs: &[ItemKind::CoolingSystem],
    },
    RecipeInfo {
        name: "Battery",
        inputs: &[ItemKind::SulfuricAcid, ItemKind::AluminaSolution, ItemKind::AluminumCasing],
        outputs: &[ItemKind::Battery, ItemKind::Water],
    },
    RecipeInfo {
        name: "Supercomputer",
        inputs: &[ItemKind::Computer, ItemKind::AiLimiter, ItemKind::HighSpeedConnector, ItemKind::Plastic],
        outputs: &[ItemKind::Supercomputer],
    },
    RecipeInfo {
        name: "Radio Control Unit",
        inputs: &[ItemKind::AluminumCasing, ItemKind::CrystalOscillator, ItemKind::Computer],
        outputs: &[ItemKind::RadioControlUnit],
    },
    RecipeInfo {
        name: "Sulfuric Acid",
        inputs: &[ItemKind::Sulfur, ItemKind::Water],
        outputs: &[ItemKind::SulfuricAcid],
    },
    RecipeInfo {
        name: "Packaged Sulfuric Acid",
        inputs: &[ItemKind::SulfuricAcid, ItemKind::EmptyCanister],
        outputs: &[ItemKind::PackagedSulfuricAcid],
    },
    RecipeInfo {
        name: "Assembly Director System",
        inputs: &[ItemKind::AdaptiveControlUnit, ItemKind::Supercomputer],
        outputs: &[ItemKind::AssemblyDirectorSystem],
    },
    RecipeInfo {
        name: "High-Speed Connector",
        inputs: &[ItemKind::Quickwire, ItemKind::Cable, ItemKind::CircuitBoard],
        outputs: &[ItemKind::HighSpeedConnector],
    },
    RecipeInfo {
        name: "Unpackage Sulfuric Acid",
        inputs: &[ItemKind::PackagedSulfuricAcid],
        outputs: &[ItemKind::SulfuricAcid, ItemKind::EmptyCanister],
    },
    RecipeInfo {
        name: "Super-State Computer",
        inputs: &[ItemKind::Computer, ItemKind::ElectromagneticControlRod, ItemKind::Battery, ItemKind::Wire],
        outputs: &[ItemKind::Supercomputer],
    },
    RecipeInfo {
        name: "Electromagnetic Control Rod",
        inputs: &[ItemKind::Stator, ItemKind::AiLimiter],
        outputs: &[ItemKind::ElectromagneticControlRod],
    },
    RecipeInfo {
        name: "Uranium Fuel Rod",
        inputs: &[ItemKind::EncasedUraniumCell, ItemKind::EncasedIndustrialBeam, ItemKind::ElectromagneticControlRod],
        outputs: &[ItemKind::UraniumFuelRod],
    },
    RecipeInfo {
        name: "Magnetic Field Generator",
        inputs: &[ItemKind::VersatileFramework, ItemKind::ElectromagneticControlRod],
        outputs: &[ItemKind::MagneticFieldGenerator],
    },
    RecipeInfo {
        name: "Sloppy Alumina",
        inputs: &[ItemKind::Bauxite, ItemKind::Water],
        outputs: &[ItemKind::AluminaSolution],
    },
    RecipeInfo {
        name: "Radio Control System",
        inputs: &[ItemKind::CrystalOscillator, ItemKind::CircuitBoard, ItemKind::AluminumCasing, ItemKind::Rubber],
        outputs: &[ItemKind::RadioControlUnit],
    },
    RecipeInfo {
        name: "Plutonium Fuel Unit",
        inputs: &[ItemKind::EncasedPlutoniumCell, ItemKind::PressureConversionCube],
        outputs: &[ItemKind::PlutoniumFuelRod],
    },
    RecipeInfo {
        name: "OC Supercomputer",
        inputs: &[ItemKind::RadioControlUnit, ItemKind::CoolingSystem],
        outputs: &[ItemKind::Supercomputer],
    },
    RecipeInfo {
        name: "Heat Sink",
        inputs: &[ItemKind::AlcladAluminumSheet, ItemKind::CopperSheet],
        outputs: &[ItemKind::HeatSink],
    },
    RecipeInfo {
        name: "Fused Modular Frame",
        inputs: &[ItemKind::HeavyModularFrame, ItemKind::AluminumCasing, ItemKind::NitrogenGas],
        outputs: &[ItemKind::FusedModularFrame],
    },
    RecipeInfo {
        name: "Empty Fluid Tank",
        inputs: &[ItemKind::AluminumIngot],
        outputs: &[ItemKind::EmptyFluidTank],
    },
    RecipeInfo {
        name: "Packaged Nitrogen Gas",
        inputs: &[ItemKind::NitrogenGas, ItemKind::EmptyFluidTank],
        outputs: &[ItemKind::PackagedNitrogenGas],
    },
    RecipeInfo {
        name: "Unpackage Nitrogen Gas",
        inputs: &[ItemKind::PackagedNitrogenGas],
        outputs: &[ItemKind::NitrogenGas, ItemKind::EmptyFluidTank],
    },
    RecipeInfo {
        name: "Instant Scrap",
        inputs: &[ItemKind::Bauxite, ItemKind::Coal, ItemKind::SulfuricAcid, ItemKind::Water],
        outputs: &[ItemKind::AluminumScrap, ItemKind::Water],
    },
    RecipeInfo {
        name: "Instant Plutonium Cell",
        inputs: &[ItemKind::NonFissileUranium, ItemKind::AluminumCasing],
        outputs: &[ItemKind::EncasedPlutoniumCell],
    },
    RecipeInfo {
        name: "Heat-Fused Frame",
        inputs: &[ItemKind::HeavyModularFrame, ItemKind::AluminumIngot, ItemKind::NitricAcid, ItemKind::Fuel],
        outputs: &[ItemKind::FusedModularFrame],
    },
    RecipeInfo {
        name: "Fertile Uranium",
        inputs: &[ItemKind::Uranium, ItemKind::UraniumWaste, ItemKind::NitricAcid, ItemKind::SulfuricAcid],
        outputs: &[ItemKind::NonFissileUranium, ItemKind::Water],
    },
    RecipeInfo {
        name: "Electric Motor",
        inputs: &[ItemKind::ElectromagneticControlRod, ItemKind::Rotor],
        outputs: &[ItemKind::Motor],
    },
    RecipeInfo {
        name: "Diluted Fuel",
        inputs: &[ItemKind::HeavyOilResidue, ItemKind::Water],
        outputs: &[ItemKind::Fuel],
    },
    RecipeInfo {
        name: "Cooling Device",
        inputs: &[ItemKind::HeatSink, ItemKind::Motor, ItemKind::NitrogenGas],
        outputs: &[ItemKind::CoolingSystem],
    },
    RecipeInfo {
        name: "Classic Battery",
        inputs: &[ItemKind::Sulfur, ItemKind::AlcladAluminumSheet, ItemKind::Plastic, ItemKind::Wire],
        outputs: &[ItemKind::Battery],
    },
    RecipeInfo {
        name: "Automated Miner",
        inputs: &[ItemKind::SteelPipe, ItemKind::IronPlate],
        outputs: &[ItemKind::PortableMiner],
    },
    RecipeInfo {
        name: "Alclad Casing",
        inputs: &[ItemKind::AluminumIngot, ItemKind::CopperIngot],
        outputs: &[ItemKind::AluminumCasing],
    },
    RecipeInfo {
        name: "Molded Steel Pipe",
        inputs: &[ItemKind::SteelIngot, ItemKind::Concrete],
        outputs: &[ItemKind::SteelPipe],
    },
    RecipeInfo {
        name: "Iron Pipe",
        inputs: &[ItemKind::IronIngot],
        outputs: &[ItemKind::SteelPipe],
    },
    RecipeInfo {
        name: "Steel Cast Plate",
        inputs: &[ItemKind::IronIngot, ItemKind::SteelIngot],
        outputs: &[ItemKind::IronPlate],
    },
    RecipeInfo {
        name: "Molded Beam",
        inputs: &[ItemKind::SteelIngot, ItemKind::Concrete],
        outputs: &[ItemKind::SteelBeam],
    },
    RecipeInfo {
        name: "Aluminum Beam",
        inputs: &[ItemKind::AluminumIngot],
        outputs: &[ItemKind::SteelBeam],
    },
    RecipeInfo {
        name: "Aluminum Rod",
        inputs: &[ItemKind::AluminumIngot],
        outputs: &[ItemKind::IronRod],
    },
    RecipeInfo {
        name: "Plastic AI Limiter",
        inputs: &[ItemKind::Quickwire, ItemKind::Plastic],
        outputs: &[ItemKind::AiLimiter],
    },
    RecipeInfo {
        name: "Distilled Silica",
        inputs: &[ItemKind::DissolvedSilica, ItemKind::Limestone, ItemKind::Water],
        outputs: &[ItemKind::Silica, ItemKind::Water],
    },
    RecipeInfo {
        name: "Quartz Purification",
        inputs: &[ItemKind::RawQuartz, ItemKind::NitricAcid],
        outputs: &[ItemKind::QuartzCrystal, ItemKind::DissolvedSilica],
    },
    RecipeInfo {
        name: "Fused Quartz Crystal",
        inputs: &[ItemKind::RawQuartz, ItemKind::Coal],
        outputs: &[ItemKind::QuartzCrystal],
    },
    RecipeInfo {
        name: "Leached Iron ingot",
        inputs: &[ItemKind::IronOre, ItemKind::SulfuricAcid],
        outputs: &[ItemKind::IronIngot],
    },
    RecipeInfo {
        name: "Basic Iron Ingot",
        inputs: &[ItemKind::IronOre, ItemKind::Limestone],
        outputs: &[ItemKind::IronIngot],
    },
    RecipeInfo {
        name: "Tempered Copper Ingot",
        inputs: &[ItemKind::CopperOre, ItemKind::PetroleumCoke],
        outputs: &[ItemKind::CopperIngot],
    },
    RecipeInfo {
        name: "Leached Copper Ingot",
        inputs: &[ItemKind::CopperOre, ItemKind::SulfuricAcid],
        outputs: &[ItemKind::CopperIngot],
    },
    RecipeInfo {
        name: "Tempered Caterium Ingot",
        inputs: &[ItemKind::CateriumOre, ItemKind::PetroleumCoke],
        outputs: &[ItemKind::CateriumIngot],
    },
    RecipeInfo {
        name: "Leached Caterium Ingot",
        inputs: &[ItemKind::CateriumOre, ItemKind::SulfuricAcid],
        outputs: &[ItemKind::CateriumIngot],
    },
    RecipeInfo {
        name: "Caterium Wire",
        inputs: &[ItemKind::CateriumIngot],
        outputs: &[ItemKind::Wire],
    },
    RecipeInfo {
        name: "Iron Wire",
        inputs: &[ItemKind::IronIngot],
        outputs: &[ItemKind::Wire],
    },
    RecipeInfo {
        name: "Infused Uranium Cell",
        inputs: &[ItemKind::Uranium, ItemKind::Silica, ItemKind::Sulfur, ItemKind::Quickwire],
        outputs: &[ItemKind::EncasedUraniumCell],
    },
    RecipeInfo {
        name: "Caterium Ingot",
        inputs: &[ItemKind::CateriumOre],
        outputs: &[ItemKind::CateriumIngot],
    },
    RecipeInfo {
        name: "Turbo Electric Motor",
        inputs: &[ItemKind::Motor, ItemKind::RadioControlUnit, ItemKind::ElectromagneticControlRod, ItemKind::Rotor],
        outputs: &[ItemKind::TurboMotor],
    },
    RecipeInfo {
        name: "Turbo Motor",
        inputs: &[ItemKind::CoolingSystem, ItemKind::RadioControlUnit, ItemKind::Motor, ItemKind::Rubber],
        outputs: &[ItemKind::TurboMotor],
    },
    RecipeInfo {
        name: "Thermal Propulsion Rocket",
        inputs: &[ItemKind::ModularEngine, ItemKind::TurboMotor, ItemKind::CoolingSystem, ItemKind::FusedModularFrame],
        outputs: &[ItemKind::ThermalPropulsionRocket],
    },
    RecipeInfo {
        name: "Quickwire Stator",
        inputs: &[ItemKind::SteelPipe, ItemKind::Quickwire],
        outputs: &[ItemKind::Stator],
    },
    RecipeInfo {
        name: "Cheap Silica",
        inputs: &[ItemKind::RawQuartz, ItemKind::Limestone],
        outputs: &[ItemKind::Silica],
    },
    RecipeInfo {
        name: "Steel Screw",
        inputs: &[ItemKind::SteelBeam],
        outputs: &[ItemKind::Screw],
    },
    RecipeInfo {
        name: "Cast Screw",
        inputs: &[ItemKind::IronIngot],
        outputs: &[ItemKind::Screw],
    },
    RecipeInfo {
        name: "Steel Rotor",
        inputs: &[ItemKind::SteelPipe, ItemKind::Wire],
        outputs: &[ItemKind::Rotor],
    },
    RecipeInfo {
        name: "Encased Industrial Pipe",
        inputs: &[ItemKind::SteelPipe, ItemKind::Concrete],
        outputs: &[ItemKind::EncasedIndustrialBeam],
    },
    RecipeInfo {
        name: "Stitched Iron Plate",
        inputs: &[ItemKind::IronPlate, ItemKind::Wire],
        outputs: &[ItemKind::ReinforcedIronPlate],
    },
    RecipeInfo {
        name: "Bolted Iron Plate",
        inputs: &[ItemKind::IronPlate, ItemKind::Screw],
        outputs: &[ItemKind::ReinforcedIronPlate],
    },
    RecipeInfo {
        name: "Radio Connection Unit",
        inputs: &[ItemKind::HeatSink, ItemKind::HighSpeedConnector, ItemKind::QuartzCrystal],
        outputs: &[ItemKind::RadioControlUnit],
    },
    RecipeInfo {
        name: "Fused Quickwire",
        inputs: &[ItemKind::CateriumIngot, ItemKind::CopperIngot],
        outputs: &[ItemKind::Quickwire],
    },
    RecipeInfo {
        name: "Recycled Plastic",
        inputs: &[ItemKind::Rubber, ItemKind::Fuel],
        outputs: &[ItemKind::Plastic],
    },
    RecipeInfo {
        name: "Uranium Fuel Unit",
        inputs: &[ItemKind::EncasedUraniumCell, ItemKind::ElectromagneticControlRod, ItemKind::CrystalOscillator, ItemKind::Rotor],
        outputs: &[ItemKind::UraniumFuelRod],
    },
    RecipeInfo {
        name: "Rigor Motor",
        inputs: &[ItemKind::Rotor, ItemKind::Stator, ItemKind::CrystalOscillator],
        outputs: &[ItemKind::Motor],
    },
    RecipeInfo {
        name: "Steeled Frame",
        inputs: &[ItemKind::ReinforcedIronPlate, ItemKind::SteelPipe],
        outputs: &[ItemKind::ModularFrame],
    },
    RecipeInfo {
        name: "Compacted Steel Ingot",
        inputs: &[ItemKind::IronOre, ItemKind::CompactedCoal],
        outputs: &[ItemKind::SteelIngot],
    },
    RecipeInfo {
        name: "Solid Steel Ingot",
        inputs: &[ItemKind::IronIngot, ItemKind::Coal],
        outputs: &[ItemKind::SteelIngot],
    },
    RecipeInfo {
        name: "Iron Alloy Ingot",
        inputs: &[ItemKind::IronOre, ItemKind::CopperOre],
        outputs: &[ItemKind::IronIngot],
    },
    RecipeInfo {
        name: "Silicon High-Speed Connector",
        inputs: &[ItemKind::Quickwire, ItemKind::Silica, ItemKind::CircuitBoard],
        outputs: &[ItemKind::HighSpeedConnector],
    },
    RecipeInfo {
        name: "Heavy Encased Frame",
        inputs: &[ItemKind::ModularFrame, ItemKind::EncasedIndustrialBeam, ItemKind::SteelPipe, ItemKind::Concrete],
        outputs: &[ItemKind::HeavyModularFrame],
    },
    RecipeInfo {
        name: "Heat Exchanger",
        inputs: &[ItemKind::AluminumCasing, ItemKind::Rubber],
        outputs: &[ItemKind::HeatSink],
    },
    RecipeInfo {
        name: "Fine Black Powder",
        inputs: &[ItemKind::Sulfur, ItemKind::CompactedCoal],
        outputs: &[ItemKind::BlackPowder],
    },
    RecipeInfo {
        name: "Electromagnetic Connection Rod",
        inputs: &[ItemKind::Stator, ItemKind::HighSpeedConnector],
        outputs: &[ItemKind::ElectromagneticControlRod],
    },
    RecipeInfo {
        name: "Insulated Crystal Oscillator",
        inputs: &[ItemKind::QuartzCrystal, ItemKind::Rubber, ItemKind::AiLimiter],
        outputs: &[ItemKind::CrystalOscillator],
    },
    RecipeInfo {
        name: "Fine Concrete",
        inputs: &[ItemKind::Silica, ItemKind::Limestone],
        outputs: &[ItemKind::Concrete],
    },
    RecipeInfo {
        name: "Crystal Computer",
        inputs: &[ItemKind::CircuitBoard, ItemKind::CrystalOscillator],
        outputs: &[ItemKind::Computer],
    },
    RecipeInfo {
        name: "Caterium Computer",
        inputs: &[ItemKind::CircuitBoard, ItemKind::Quickwire, ItemKind::Rubber],
        outputs: &[ItemKind::Computer],
    },
    RecipeInfo {
        name: "Caterium Circuit Board",
        inputs: &[ItemKind::Plastic, ItemKind::Quickwire],
        outputs: &[ItemKind::CircuitBoard],
    },
    RecipeInfo {
        name: "Silicon Circuit Board",
        inputs: &[ItemKind::CopperSheet, ItemKind::Silica],
        outputs: &[ItemKind::CircuitBoard],
    },
    RecipeInfo {
        name: "Quickwire Cable",
        inputs: &[ItemKind::Quickwire, ItemKind::Rubber],
        outputs: &[ItemKind::Cable],
    },
    RecipeInfo {
        name: "Insulated Cable",
        inputs: &[ItemKind::Wire, ItemKind::Rubber],
        outputs: &[ItemKind::Cable],
    },
    RecipeInfo {
        name: "Ficsonium",
        inputs: &[ItemKind::PlutoniumWaste, ItemKind::SingularityCell, ItemKind::DarkMatterResidue],
        outputs: &[ItemKind::Ficsonium],
    },
    RecipeInfo {
        name: "Ficsonium Fuel Rod",
        inputs: &[ItemKind::Ficsonium, ItemKind::ElectromagneticControlRod, ItemKind::FicsiteTrigon, ItemKind::ExcitedPhotonicMatter],
        outputs: &[ItemKind::FicsoniumFuelRod, ItemKind::DarkMatterResidue],
    },
    RecipeInfo {
        name: "Singularity Cell",
        inputs: &[ItemKind::NuclearPasta, ItemKind::DarkMatterCrystal, ItemKind::IronPlate, ItemKind::Concrete],
        outputs: &[ItemKind::SingularityCell],
    },
    RecipeInfo {
        name: "Ballistic Warp Drive",
        inputs: &[ItemKind::ThermalPropulsionRocket, ItemKind::SingularityCell, ItemKind::SuperpositionOscillator, ItemKind::DarkMatterCrystal],
        outputs: &[ItemKind::BallisticWarpDrive],
    },
    RecipeInfo {
        name: "Iodine-Infused Filter",
        inputs: &[ItemKind::GasFilter, ItemKind::Quickwire, ItemKind::AluminumCasing],
        outputs: &[ItemKind::IodineInfusedFilter],
    },
    RecipeInfo {
        name: "Quickwire",
        inputs: &[ItemKind::CateriumIngot],
        outputs: &[ItemKind::Quickwire],
    },
    RecipeInfo {
        name: "Solid Biofuel",
        inputs: &[ItemKind::Biomass],
        outputs: &[ItemKind::SolidBiofuel],
    },
    RecipeInfo {
        name: "Hog Protein",
        inputs: &[ItemKind::HogRemains],
        outputs: &[ItemKind::AlienProtein],
    },
    RecipeInfo {
        name: "Spitter Protein",
        inputs: &[ItemKind::SpitterRemains],
        outputs: &[ItemKind::AlienProtein],
    },
    RecipeInfo {
        name: "Biomass (Mycelia)",
        inputs: &[ItemKind::Mycelia],
        outputs: &[ItemKind::Biomass],
    },
    RecipeInfo {
        name: "Power Shard (1)",
        inputs: &[ItemKind::BluePowerSlug],
        outputs: &[ItemKind::PowerShard],
    },
    RecipeInfo {
        name: "Black Powder",
        inputs: &[ItemKind::Coal, ItemKind::Sulfur],
        outputs: &[ItemKind::BlackPowder],
    },
    RecipeInfo {
        name: "Alien Power Matrix",
        inputs: &[ItemKind::SamFluctuator, ItemKind::PowerShard, ItemKind::SuperpositionOscillator, ItemKind::ExcitedPhotonicMatter],
        outputs: &[ItemKind::AlienPowerMatrix, ItemKind::DarkMatterResidue],
    },
    RecipeInfo {
        name: "Stinger Protein",
        inputs: &[ItemKind::StingerRemains],
        outputs: &[ItemKind::AlienProtein],
    },
    RecipeInfo {
        name: "Hatcher Protein",
        inputs: &[ItemKind::HatcherRemains],
        outputs: &[ItemKind::AlienProtein],
    },
    RecipeInfo {
        name: "Alien DNA Capsule",
        inputs: &[ItemKind::AlienProtein],
        outputs: &[ItemKind::AlienDnaCapsule],
    },
    RecipeInfo {
        name: "Biomass (Alien Protein)",
        inputs: &[ItemKind::AlienProtein],
        outputs: &[ItemKind::Biomass],
    },
    RecipeInfo {
        name: "Iron Rebar",
        inputs: &[ItemKind::IronRod],
        outputs: &[ItemKind::IronRebar],
    },
    RecipeInfo {
        name: "Homing Rifle Ammo",
        inputs: &[ItemKind::RifleAmmo, ItemKind::HighSpeedConnector],
        outputs: &[ItemKind::HomingRifleAmmo],
    },
    RecipeInfo {
        name: "Stun Rebar",
        inputs: &[ItemKind::IronRebar, ItemKind::Quickwire],
        outputs: &[ItemKind::StunRebar],
    },
    RecipeInfo {
        name: "Gas Filter",
        inputs: &[ItemKind::Fabric, ItemKind::Coal, ItemKind::IronPlate],
        outputs: &[ItemKind::GasFilter],
    },
    RecipeInfo {
        name: "Gas Nobelisk",
        inputs: &[ItemKind::Nobelisk, ItemKind::Biomass],
        outputs: &[ItemKind::GasNobelisk],
    },
    RecipeInfo {
        name: "Polyester Fabric",
        inputs: &[ItemKind::PolymerResin, ItemKind::Water],
        outputs: &[ItemKind::Fabric],
    },
    RecipeInfo {
        name: "Fabric",
        inputs: &[ItemKind::Mycelia, ItemKind::Biomass],
        outputs: &[ItemKind::Fabric],
    },
    RecipeInfo {
        name: "Synthetic Power Shard",
        inputs: &[ItemKind::TimeCrystal, ItemKind::DarkMatterCrystal, ItemKind::QuartzCrystal, ItemKind::ExcitedPhotonicMatter],
        outputs: &[ItemKind::PowerShard, ItemKind::DarkMatterResidue],
    },
    RecipeInfo {
        name: "Power Shard (5)",
        inputs: &[ItemKind::PurplePowerSlug],
        outputs: &[ItemKind::PowerShard],
    },
    RecipeInfo {
        name: "Power Shard (2)",
        inputs: &[ItemKind::YellowPowerSlug],
        outputs: &[ItemKind::PowerShard],
    },
    RecipeInfo {
        name: "Pulse Nobelisk",
        inputs: &[ItemKind::Nobelisk, ItemKind::CrystalOscillator],
        outputs: &[ItemKind::PulseNobelisk],
    },
    RecipeInfo {
        name: "Shatter Rebar",
        inputs: &[ItemKind::IronRebar, ItemKind::QuartzCrystal],
        outputs: &[ItemKind::ShatterRebar],
    },
    RecipeInfo {
        name: "Turbo Rifle Ammo",
        inputs: &[ItemKind::RifleAmmo, ItemKind::AluminumCasing, ItemKind::PackagedTurbofuel],
        outputs: &[ItemKind::TurboRifleAmmo],
    },
    RecipeInfo {
        name: "Turbo Rifle Ammo",
        inputs: &[ItemKind::RifleAmmo, ItemKind::AluminumCasing, ItemKind::Turbofuel],
        outputs: &[ItemKind::TurboRifleAmmo],
    },
    RecipeInfo {
        name: "Nuke Nobelisk",
        inputs: &[ItemKind::Nobelisk, ItemKind::EncasedUraniumCell, ItemKind::SmokelessPowder, ItemKind::AiLimiter],
        outputs: &[ItemKind::NukeNobelisk],
    },
    RecipeInfo {
        name: "Rifle Ammo",
        inputs: &[ItemKind::CopperSheet, ItemKind::SmokelessPowder],
        outputs: &[ItemKind::RifleAmmo],
    },
    RecipeInfo {
        name: "Explosive Rebar",
        inputs: &[ItemKind::IronRebar, ItemKind::SmokelessPowder, ItemKind::SteelPipe],
        outputs: &[ItemKind::ExplosiveRebar],
    },
    RecipeInfo {
        name: "Cluster Nobelisk",
        inputs: &[ItemKind::Nobelisk, ItemKind::SmokelessPowder],
        outputs: &[ItemKind::ClusterNobelisk],
    },
    RecipeInfo {
        name: "Nobelisk",
        inputs: &[ItemKind::BlackPowder, ItemKind::SteelPipe],
        outputs: &[ItemKind::Nobelisk],
    },
    RecipeInfo {
        name: "Smokeless Powder",
        inputs: &[ItemKind::BlackPowder, ItemKind::HeavyOilResidue],
        outputs: &[ItemKind::SmokelessPowder],
    },
    RecipeInfo {
        name: "Biomass (Leaves)",
        inputs: &[ItemKind::Leaves],
        outputs: &[ItemKind::Biomass],
    },
    RecipeInfo {
        name: "Biomass (Wood)",
        inputs: &[ItemKind::Wood],
        outputs: &[ItemKind::Biomass],
    },
    RecipeInfo {
        name: "Reinforced Iron Plate",
        inputs: &[ItemKind::IronPlate, ItemKind::Screw],
        outputs: &[ItemKind::ReinforcedIronPlate],
    },
    RecipeInfo {
        name: "Concrete",
        inputs: &[ItemKind::Limestone],
        outputs: &[ItemKind::Concrete],
    },
    RecipeInfo {
        name: "Screw",
        inputs: &[ItemKind::IronRod],
        outputs: &[ItemKind::Screw],
    },
    RecipeInfo {
        name: "Cable",
        inputs: &[ItemKind::Wire],
        outputs: &[ItemKind::Cable],
    },
    RecipeInfo {
        name: "Wire",
        inputs: &[ItemKind::CopperIngot],
        outputs: &[ItemKind::Wire],
    },
    RecipeInfo {
        name: "Copper Ingot",
        inputs: &[ItemKind::CopperOre],
        outputs: &[ItemKind::CopperIngot],
    },
];
